- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENCE
- README.md
- docs/README.md
- docs/runbooks/README.md
- metadata.json
Adds a range of repository best practice documentation.
* MIT Licence
* Badges to main README
* Code of Conduct
* Contributing Guidelines
* Docs README
* Example runbook docs setup
* metadata.json
Fixes MLPAB-19
Used the [OPG Technical Guidance Repo Readme Principles](https://docs.opg.service.justice.gov.uk/documentation/guides/repo_principles.html) to ensure appropriate documentation is added.
None
> MLPAB-19 Repo Guidelines

- .github/workflows/workflow_path_to_live.yml
- README.md
Ensuring unit tests run on merges to main.
Fixes MLPAB-23
> MLAPB-23: Add Go unit tests/codecov step to path to live

- .github/workflows/docker_job.yml
- .github/workflows/terraform_environment_job.yml
- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
Store docker images for later deployment to ECS
Fixes MLPAB-55
- Create areusable workflow to build, scan and push imaage to ECR
- Add build, scan, push job to PR workflow
- Add build, scan, push job to Path to Live
- fix terraform session names
- push scan results to github security tab
- https://github.com/aws-actions/amazon-ecr-login
> MLPAB-55 - Build and push app image to ECR

- .github/workflows/analysis-codeql.yml
- .gitignore
Provide feedback to developers on Golang code quality
Fixes MLPAB-56
- Add CodeQL analysis
- https://codeql.github.com/docs/codeql-overview/about-codeql/
> MLPAB-56 - Add codeql analysis for go

- .github/workflows/docker_job.yml
Change the env var name for the repository
Fixes MLPAB-62
> MLPAB-62 Change variable names

- .github/workflows/terraform_environment_job.yml
- .pre-commit-config.yaml
- terraform/environment/.envrc
- terraform/environment/README.md
- terraform/environment/iam_ecs_execution_role.tf
- terraform/environment/iam_ecs_task_roles.tf
- terraform/environment/region/.terraform.lock.hcl
- terraform/environment/region/ecs.tf
- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/region/modules/app/terraform.tf
- terraform/environment/region/modules/app/variables.tf
- terraform/environment/region/modules/application_logs/cloudwatch_log_group.tf
- terraform/environment/region/modules/application_logs/outputs.tf
- terraform/environment/region/modules/application_logs/terraform.tf
- terraform/environment/region/modules/application_logs/variables.tf
- terraform/environment/region/network.tf
- terraform/environment/region/terraform.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Deploy the app image to ECS
Fixes MLPAB-17
- start a region module
- create an ECS cluster
- create encrypted application logging
- create ECS service for app
- Create a global ECS execution IAM role for environment
- Create a global ECS service task IAM role for environment
- https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_Operations.html
> MLPAB-17 - Deploy app to ECS

- .github/workflows/workflow_terraform_environment_cleanup.yml
- scripts/workspace_cleanup.sh
Address issues with frst run of cleanup
Fixes MLPAB-####
- Lint bash script with shellcheck
- Correct reference to deploy key
- https://www.shellcheck.net/
> MLPAB-73 - Fixes to PR environment cleanup

- .github/dependabot.yml
Keep packages up to date
Fixes MLPAB-115
- add a Dependabot updates configuration
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
> MLPA-115 - Create package update PRs for all ecosystems

- terraform/environment/region/ecs.tf
- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/region/modules/app/variables.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Fixes MLPAB-141
- create a variable that can hold all env vars for app
- pass env vars variable object through to ECS
- configure values for each environment with tfvars
> MLPAB-141 - Configure app_public_url env var value for each environment

- terraform/account/.terraform.lock.hcl
- terraform/account/backup_role.tf
- terraform/account/region/backup_vault.tf
Create a vault to keep backups in
Fixes MLPAB-150
- Create a global AWS Backup role
- Create a regional vault
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_vault
- https://docs.aws.amazon.com/aws-backup/latest/devguide/iam-service-roles.html
> MLPAB-150 - Create a backup role and a backup regional vault

- terraform/account/region/backup_vault.tf
The vault resource requires a region provider
Fixes MLPAB-150
> MLPAB-150 - Fix - Put the provider for the backup vault resource

- app/internal/page/app.go
- app/internal/page/choose_attorneys_address.go
- app/internal/page/choose_attorneys_address_test.go
- app/internal/page/data.go
- app/internal/page/paths.go
- app/internal/page/restrictions.go
- app/internal/page/restrictions_test.go
- app/internal/page/task_list.go
- app/internal/page/task_list_test.go
- app/internal/page/want_replacement_attorneys.go
- app/internal/page/want_replacement_attorneys_test.go
- app/internal/page/when_can_the_lpa_be_used.go
- app/internal/page/when_can_the_lpa_be_used_test.go
- app/lang/cy.json
- app/lang/en.json
- app/web/template/restrictions.gohtml
- app/web/template/task_list.gohtml
- app/web/template/when_can_the_lpa_be_used.gohtml
- cypress/e2e/choose-attorneys-address.cy.js
- cypress/e2e/restrictions.cy.js
- cypress/e2e/want-replacement-attorneys.cy.js
- cypress/e2e/when-can-the-lpa-be-used.cy.js
Also went back and made the "when can the LPA be used" page skippable as per the prototype, and made the pages flow once you start "choose attorneys"
> MLPAB-101 Restrictions

- terraform/account/secrets_manager_secret.tf
Create secret to store value of api key where it can be retrieved by the app
Fixes MLPAB-160
- Create encrypted secret
> MLPAB-160 - Create secret for pay api key

- app/internal/page/check_your_lpa.go
- app/internal/page/check_your_lpa_test.go
- app/internal/page/data.go
- app/internal/page/task_list.go
- app/internal/page/task_list_test.go
- cypress/e2e/check-your-lpa.cy.js
Realised after a manual test that the status for check your LPA wasn't updating - quick fix to add that in here.
Fixes MLPAB-106.
> MLPAB-106: Fix check status

- .github/workflows/docker_job.yml
- .github/workflows/workflow_pr.yml
Fix issue on Path to Live where additional tags are not being set and pushed.
Fixes MLPAB-217
- use gtihub.head_ref as env var isn't set here
> MLPAB-217 - Pipeline doesn't push additional main branch tags

- app/web/template/layout/page.gohtml
Just spotted this when clicking around
> Fix back link when welsh

- .github/workflows/workflow_path_to_live.yml
Fix missing permission on pipeline
Fixes MLPAB-216
> MLPAB-216 - Add id-token permission to Path to Live

- .github/workflows/docker_job.yml
Trivvy is unable to push notifications
Fixes MLPAB-216
> MLPAB-216 - Remove reduction of role in docker job

- .github/workflows/docker_job.yml
> declare job level permissions

- app/go.mod
- app/go.sum
- app/main.go
> MLPAB-31 Wrap http client with otelhttp package

- app/lang/cy.json
I was clicking through and saw I'd put this in the wrong place
> Put email address in correct welsh key

- .github/workflows/workflow_path_to_live.yml
- .secrets.baseline
Fix path to live
Fixes MLPAB-78
> MLPAB-78-fix - always rebuild on path to live

- .github/workflows/docker_job.yml
Path to live failed to recognise the expressin in the if statement for tagging
Fixes MLPAB-538
- wrap the expression in `${{ }}`
- https://docs.github.com/en/actions/learn-github-actions/expressions
> MLPAB-528 - Fix Path to Live tag condition

- app/internal/onelogin/client.go
- app/internal/onelogin/exchange.go
- app/internal/onelogin/exchange_test.go
- app/internal/onelogin/user_info.go
- app/internal/onelogin/user_info_test.go
- app/internal/page/app.go
- app/internal/page/auth_redirect.go
- app/internal/page/auth_redirect_test.go
- app/internal/page/identity_with_one_login.go
- app/internal/page/identity_with_one_login_callback.go
- app/internal/page/identity_with_one_login_callback_test.go
- app/internal/page/identity_with_one_login_test.go
- app/internal/page/login.go
- app/internal/page/login_test.go
- app/internal/secrets/secrets.go
- app/web/template/identity_with_one_login_callback.gohtml
- localstack-init.sh
- mocks/GOVUKSignIn/main.go
- terraform/environment/region/modules/app/ecs.tf
After https://github.com/ministryofjustice/opg-modernising-lpa/pull/293
> MLPAB-612 Verify the One Login returned CoreIdentityJWT property

- app/internal/page/app.go
- app/internal/page/app_test.go
- app/internal/page/auth_redirect.go
- app/internal/page/auth_redirect_test.go
- app/internal/page/certificate_provider_login.go
- app/internal/page/certificate_provider_login_callback.go
- app/internal/page/certificate_provider_login_callback_test.go
- app/internal/page/certificate_provider_login_test.go
- app/internal/page/certificate_provider_start.go
- app/internal/page/certificate_provider_start_test.go
- app/internal/page/data.go
- app/internal/page/identity_with_one_login_callback.go
- app/internal/page/identity_with_one_login_callback_test.go
- app/internal/page/identity_with_one_login_test.go
- app/internal/page/login.go
- app/internal/page/paths.go
- app/internal/page/sessions.go
- app/internal/page/your_details.go
- app/internal/page/your_details_test.go
- app/main.go
- app/web/template/certificate_provider_start.gohtml
- app/web/template/certificate_provider_your_details.gohtml
- app/web/template/layout/page.gohtml
- cypress/e2e/certificate-provider/start.cy.js
- cypress/e2e/certificate-provider/your-details.cy.js
I've also added https://opgtransform.atlassian.net/browse/MLPAB-669 and https://opgtransform.atlassian.net/browse/MLPAB-670 to the backlog because I think the data should be done differently.
> MLPAB-660 Start page and ID for certificate provider

- app/internal/page/certificateprovider/register.go
- app/internal/page/paths.go
- app/web/template/certificate_provider_read_the_lpa.gohtml
- cypress/e2e/certificate-provider/read-the-lpa.cy.js
Just defaulting to the existing template we have until we get any changes from content/design.
Fixes MLPAB-662.
> MLPAB-662: Certificate provider reads the LPA

- .github/workflows/workflow_path_to_live.yml
- .secrets.baseline
Path to live failed due to missing secrets
Fixes MLPAB-680
- fix preprod remove ingress job
> MLPAB-680 - Fix - Add secrets to remove ingress

- app/internal/app/app.go
- app/internal/page/auth_redirect.go
- app/internal/page/auth_redirect_test.go
- app/internal/page/donor/login.go
- app/internal/page/donor/login_callback.go
- app/internal/page/donor/login_callback_test.go
- app/internal/page/donor/login_test.go
- app/internal/page/donor/register.go
- app/internal/page/error_test.go
- app/internal/page/paths.go
- app/main.go
- web/template/start.gohtml
This has been annoying me since doing the certificate provider version
> Refactor donor login handlers to be like certificateprovider

- app/internal/actor/donor.go
- app/internal/actor/person_test.go
- app/internal/form/address_form_test.go
- app/internal/page/certificateprovider/check_your_name.go
- app/internal/page/certificateprovider/check_your_name_test.go
- app/internal/page/certificateprovider/enter_reference_number.go
- app/internal/page/certificateprovider/enter_reference_number_test.go
- app/internal/page/certificateprovider/register_test.go
- app/internal/page/data.go
- app/internal/page/donor/about_payment_test.go
- app/internal/page/donor/certificate_provider_details_test.go
- app/internal/page/donor/choose_attorneys_test.go
- app/internal/page/donor/choose_people_to_notify_test.go
- app/internal/page/donor/choose_replacement_attorneys_address.go
- app/internal/page/donor/choose_replacement_attorneys_test.go
- app/internal/page/donor/mock_test.go
- app/internal/page/donor/payment_confirmation_test.go
- app/internal/page/donor/resend_witness_code_test.go
- app/internal/page/donor/task_list_test.go
- app/internal/page/donor/your_address_test.go
- app/internal/page/donor/your_chosen_identity_options.go
- app/internal/page/donor/your_details_test.go
- app/internal/page/fixtures.go
- app/internal/page/share_code_test.go
- app/internal/page/testing_start.go
- app/internal/page/testing_start_test.go
- app/internal/place/client_test.go
Since I went through what we store I spotted some things that aren't used now
> Remove unused data

- .github/workflows/terraform_environment_job.yml
Fix path to live
Fixes MLPAB-750
- Use a condition so that commenting on a PR doesn't happen when on the main branch
> MLPAB-750 - don't try to write PR comments on the path to live

- app/main_test.go
- lang/cy.json
Tests got missed after a reorg of directories at some point.
Fixes MLPAB-771
> MLPAB-771: Fix path for translations and add missing keys to cy

- .github/workflows/detect_changes_to_app_job.yml
Ensure that changes to /web and /lang trigger a build of the docker image and a deployment of the same.
Fixes MLPAB-797
- add new paths to git diff command
> MLPAB-797 - detect changes in lang and web

- cypress/e2e/certificate-provider/certificate-provided.cy.js
- lang/cy.json
- lang/en.json
- web/template/certificate_provided.gohtml
> MLPAB-836: Update certificate provided with new content

- terraform/account/autoscaling_role.tf
Set up autoscaling for MLPAB
Fixes MLPAB-812
- take management of the ecs service linked role
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-auto-scaling.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_service_linked_role.html
> MLPAB-812 - manage ecs autoscale service role

- terraform/account/terraform.tfvars.json
Test DR/HA features
Fixes MLPAB-912
- Provision London region account resources
> MLPAB-912 - Deploy second region account resources

- terraform/account/region/outputs.tf
- terraform/account/region/sns_autoscaling_alarms.tf
Provide autoscaling alarms with their own SNS topic
Fixes MLPAB-955
- create an encrypted sns topic with feedback monitoring
> MLPAB-955 - Create an autoscaling_alarms sns topic for each region in each account

- terraform/account/regions.tf
- terraform/account/terraform.tfvars.json
Clean up after second region testing
Fixes MLPAB-971
- remove second region account module
> MLPAB-971 - Remove second region account resources

- terraform/environment/region/modules/app/alb.tf
Redirect to maintenance pages hosted outside of this service
Fixes MLPAB-871
- update the redirect config to point to new pages
> MLPAB-871 - Use new maintenance page placeholders

- .github/workflows/workflow_destroy_pr_environment.yml
Fix destroy env job by passing correct secret and variable
Fixes MLPAB-1051
> MLPAB-1051 - fix name of variable

- .github/workflows/dispatch_deploy_to_ur_environment.yml
- .github/workflows/workflow_path_to_live.yml
Fix failure on path to live and the same error that would occur on the ur workflow
Fixes MLPAB-1039
- correct the name of the job that the output is taken from when managing environment ingress
> MLPAB-1039 - fix path to live and ur workflows

- web/template/dashboard.gohtml
- web/template/fixtures.gohtml
...and fix "complete all" in fixtures
> MLPAB-1093 Link to start of journey from dashboard if your details not complete

- terraform/environment/.terraform.lock.hcl
- terraform/environment/reduced_fees/main.tf
Update to AWS provider for Terraform fixes issue provisioning Eventbridge Pipes
Fixes MLPAB-1127
- add source parameters
> MLPAB-1127 - fix pipes config

- terraform/environment/reduced_fees/main.tf
Fixes MLPAB-1127
- add missing source parameters
- remove empty target parameters
> MLPAB-1127 - add other source parameters

- terraform/environment/region/modules/uploads_s3_bucket/data_sources.tf
This fixes access denied errors by using the correct bucket for access logging.
> MLPAB-1166 - fix path to s3 access logs

- terraform/account/region/network.tf
Prepare for a the av lambda to be able to egress the VPC
Fixes MLPAB-1163
- create security group and rule permitting egress
> MLPAB-1163 - create an egress security group for lambda

- terraform/account/s3_replication_role.tf
Create a role to be used for replcition
Fixes MLPAB-1196
> MLPAB-1196 - create global S3 replication role

- terraform/account/region/waf.tf
Otherwise you can't upload PDFs...
> MLPAB-1191 Ignore the CrossSiteScripting_BODY WAF rule

- terraform/account/parameters.tf
- terraform/account/terraform.tf
Allow access to certain people or systems outside of our regular allow list 
Fixes MLPAB-1303
- https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html#what-is-a-parameter
> MLPAB-1303 - create a paramter to hold additional CIDR blocks for custom access

- .github/workflows/workflow_path_to_live.yml
- scripts/workspace_cleanup.sh
- terraform/environment/terraform.tfvars.json
Create and keep a demo environment up to date with production
Fixes MLPAB-1319
- add deploy to demo to path to live
- protect demo environment
> MLPAB-1319 demo environment required for mlpa

- cypress/e2e/donor/confirm-your-identity-and-sign.cy.js
- lang/en.json
> MLPAB-1311: Update checkbox label

- .github/workflows/detect_changes_to_app_job.yml
Renovate PRs for go packages were not building and testing the image
Fixes MLPAB-1356
- add go.mod to detect changes job
> MLPAB-1356 - Detect changes - build image if go.mod changes

- terraform/account/.terraform.lock.hcl
- terraform/account/region/modules/dns_firewall/main.tf
Restrict egress from network
Fixes MLPAB-1372
- add service specific DNS entries
> MLPAB-1372 - add more allowed DNS names

- internal/notify/client.go
- internal/notify/client_test.go
- terraform/environment/region/modules/app/ecs.tf
I didn't realise we were defaulting the value if the envvar was "", I've set the value instead of reverting the change as this matches what we do with Pay
> Set notify base url env var

- internal/page/donor/payment_confirmation.go
- internal/page/donor/payment_confirmation_test.go
- internal/page/donor/upload_evidence.go
- internal/page/donor/upload_evidence_test.go
- lang/cy.json
- lang/en.json
- web/template/payment_confirmation.gohtml
- web/template/upload_evidence.gohtml
Varies buttons and content based on fee type on upload evidence and payment confirmation pages.
Fixes MLPAB-1025, MLPAB-1391
> MLPAB-1025, MLPAB-1391: Fee content updates

- .github/workflows/dispatch_change_dns_target_region.yml
- .github/workflows/dispatch_manage_public_access_ur_environment.yml
- .github/workflows/terraform_account_job.yml
Refactor versioning for terraform so that it can be easily maintained
Fixes MLPAB-1405
- get the terraform version to use in Github Actions from versions.tf
- fix location of versions.tf for account level configuration
> MLPAB-1405 - Get and set terraform version using version.tf

- .github/workflows/workflow_pr.yml
- terraform/account/region/vpc_endpoints.tf
Direct requests to AWS services via a VPC endpoint to reduce the egress vector through the internet gateway
Fixes MLPAB-1466
- create a gateway endpoint for s3
- create a gateway endpoint for dynamodb
> MLPAB-1466 - Create Gateway endpoints

- docker/event-received/Dockerfile
- docker/mlpa/Dockerfile
- docker/mock-notify/Dockerfile
- docker/mock-onelogin/Dockerfile
- docker/mock-os-api/Dockerfile
Switch to alpine for smaller container and fewer vulns
> Switch to alpine for smaller container and fewer vulns

- .github/workflows/ui_test_job.yml
- internal/app/trigger_build
Fixes MLPAB-1477
- tag session name to identify actions required for oidc roles
- use new oidc role for ECR pull operations
> MLPAB-1477 - replace credentials with oidc role

- internal/app/triggerbuild
- terraform/account/region/vpc_endpoints.tf
Roll back the interface endpoint policies
Fixes MLPAB-1487
> MLPAB-1487 - ecs unable to pull image from ecr after enabling tighter policies on vpc endpoints

- terraform/environment/region/modules/uploads_s3_bucket/lambda.tf
Move documents quickly when enabled
Fixes MLPAB-1514
Set schedule to 2 minutes
> MLAPB-1514 - run replication job creation lambda every 2 mintues

- Makefile
- cmd/event-received/handlers_test.go
- cmd/event-received/main.go
- terraform/environment/region/modules/event_received/lambda.tf
To match [specification](https://ministryofjustice.github.io/opg-event-store/domains/POAS/events/reduced-fee-approved/).
Fixes MLPAB-##
Explain how your code addresses the purpose of the change
> Rename `fee-approved` -> `reduced-fee-approved`

- Makefile
- cmd/event-received/handlers_test.go
- cmd/event-received/main.go
- terraform/environment/region/modules/event_received/lambda.tf
To match [specification](https://ministryofjustice.github.io/opg-event-store/domains/POAS/events/reduced-fee-declined/).
> Rename `fee-denied` -> `reduced-fee-declined`

- web/template/layout/page.gohtml
> MLPAB-1511: Set html lang based on AppData.Lang

- Makefile
- go.sum
- internal/app/uid_store.go
- internal/app/uid_store_test.go
I should have tested this step locally on the last PR - all looks to be hooked up now.
Fixes MLPAB-1636
> MLPAB-1636: Update UID store UID reference

- terraform/environment/terraform.tfvars.json
Fixes MLPAB-1691
- specify a prod like environment called codesign
> MLPAB-1691 - create a codesign environment

- .github/workflows/docker_job.yml
Fix missing tag on path to live run
Fixes MLPAB-1684
- Tag image
> MLPAB-1684 - make sure to tag without the main prefix too

- internal/page/donor/mock_test.go
- internal/page/mock_test.go
- internal/sesh/sesh.go
I saw https://go.dev/blog/deadcode and this is what it found
> Remove unused code

- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/region/modules/mock_onelogin/ecs.tf
Fix issues that arise when deployng to demo env on path to live
Fixes MLPAB-1698
- differentiate task definition family names
> MLPAB-1698 - differentiate task definition families

- terraform/account/region/sns_topics.tf
Share an SNS topic with encryption
Fixes MLPAB-1700
- create an account level SNS topic for health check alarms
> MLPAB-1700 - Create a health check SNS topic with encryption

- terraform/account/region/sns_topics.tf
The resources for health checks need to be global in order to check from multiple regions
Fixes MLPAB-1700
- create new global resource for sns topic
> MLPAB-1700 - This sns topic must be global

- docker/mock-lpa-store/mock-lpa-store-config.yaml
- internal/lpastore/client.go
- internal/lpastore/client_test.go
Also see https://github.com/ministryofjustice/opg-data-lpa-store/pull/72
> MLPAB-1637 Add the other data to the lpa store submission

- internal/lpastore/client.go
- internal/lpastore/client_test.go
- internal/page/fixtures/donor.go
1. Fixes the issue (which has been there for a while) with donor fixtures not providing the correct replacement attorney decision options
2. Send correct attorney stuff
> MLPAB-1637 Fix sending bad fields to lpastore

- terraform/environment/terraform.tfvars.json
> MLPAB-1639 Add arns to enable sending updates to lpa store

- cmd/event-received/cloud_watch_event_handler_test.go
- internal/actor/donor_provided.go
- internal/actor/donor_provided_test.go
- internal/lpastore/client.go
- internal/lpastore/client_test.go
- internal/page/donor/confirm_your_certificate_provider_is_not_related.go
- internal/page/donor/confirm_your_certificate_provider_is_not_related_test.go
- internal/page/donor/register.go
- internal/uid/client_test.go
- lang/en.json
For after https://github.com/ministryofjustice/opg-data-lpa-store/pull/93 is merged
> MLPAB-1531 Send when certificate provider not related was confirmed to lpastore

- terraform/account/region/sns_topics.tf
App insights Ops Items need an sns topic
Fixes MLPAB-1062
- Create an account level region sns topic
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/applicationinsights_application
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic
> MLPAB-1062 - Create an sns topic for cloudwatch app insghts

- .github/workflows/workflow_destroy_pr_environment.yml
Restore step that installs the workspace manager tool
Fixes MLPAB-1906
> MLPAB-1906 fix workspace tool

- terraform/account/region/vpc_endpoints.tf
> MLPAB-1785 Add security groups to opensearch vpc endpoint

- Makefile
- terraform/account/README.md
- terraform/account/region/README.md
- terraform/account/region/modules/antivirus_definitions/README.md
- terraform/account/region/modules/dns_firewall/README.md
- terraform/account/region/modules/s3_batch_manifests/README.md
- terraform/account/region/modules/s3_bucket_event_notifications/README.md
- terraform/environment/README.md
- terraform/environment/global/README.md
- terraform/environment/region/README.md
- terraform/environment/region/modules/app/README.md
- terraform/environment/region/modules/application_logs/README.md
- terraform/environment/region/modules/ecs_autoscaling/README.md
- terraform/environment/region/modules/event_bus/README.md
- terraform/environment/region/modules/event_received/README.md
- terraform/environment/region/modules/fault_injection_simulator_experiments/README.md
- terraform/environment/region/modules/lambda/README.md
- terraform/environment/region/modules/mock_onelogin/README.md
- terraform/environment/region/modules/s3_antivirus/README.md
- terraform/environment/region/modules/uploads_s3_bucket/README.md
Keep terraform documentation up to date
- Add Makefile target to update all docs
- update all docs
> Update terraform docs

- .pre-commit-config.yaml
- cypress/e2e/supporter/manage-team-members.cy.js
- internal/app/app.go
- internal/app/member_store.go
- internal/app/member_store_test.go
- internal/page/fixtures/donor.go
- internal/page/fixtures/supporter.go
- internal/page/supporter/invite_member.go
- internal/page/supporter/invite_member_test.go
- internal/page/supporter/manage_team_members.go
- internal/page/supporter/manage_team_members_test.go
- internal/page/supporter/mock_MemberStore_test.go
- internal/page/supporter/mock_test.go
- internal/page/supporter/register.go
- internal/page/supporter/register_test.go
- lang/cy.json
- lang/en.json
- package.json
- web/template/supporter/manage_team_members.gohtml
- yarn.lock
> MLPAB-1748: Allow resending invite when invite is expired

- terraform/environment/region/modules/application_logs/cloudwatch_log_group.tf
Make it easier to query application logs by matching the logging standard and surfacing useful information
Fixes MLPAB-1977
- filter log streams that are less relevant
- make result headings based on logging standard
> MLPAB-1977 - Update app logs query to improve readability

- terraform/environment/region/modules/lambda/iam.tf
- terraform/environment/region/modules/lambda/main.tf
Fixes MLPAB-1991
- add logging config to lambda function
- allow log encryption
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#logging_config
> MLPAB-1991 fix logging in lambda function

- terraform/account/README.md
- terraform/account/opensearch_kms.tf
Use customer managed key encryption for Opensearch
Fixes MLPAB-2012
- Create replicated encryption key
- https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-encryption.html
> MLPAB-2012 - Create a CMK for opensearch

- internal/templatefn/fn.go
- internal/templatefn/fn_test.go
- web/template/attorney/code_of_conduct.gohtml
- web/template/certificateprovider/who_is_eligible.gohtml
- web/template/donor/lpa_details_saved.gohtml
- web/template/donor/need_help_signing_confirmation.gohtml
- web/template/donor/we_have_updated_your_details.gohtml
- web/template/layout/notification-banner.gohtml
- web/template/lpa_deleted.gohtml
- web/template/lpa_withdrawn.gohtml
- web/template/supporter/dashboard.gohtml
- web/template/supporter/manage_team_members.gohtml
- web/template/supporter/organisation_created.gohtml
- web/template/supporter/organisation_deleted.gohtml
- web/template/supporter/organisation_details.gohtml
- web/template/supporter/suspended.gohtml
- web/template/supporter/view_lpa.gohtml
We probably should have made this a template sooner
> Update to use notification-banner layout in other places

- cypress/e2e/supporter/manage-team-members.cy.js
- web/template/layout/login-header.gohtml
> MLPAB-1952: Default to manage team members view

- cmd/enumerator/main.go
- cmd/enumerator/main_test.go
- internal/actor/enum_attorneysact.go
- internal/actor/enum_canbeusedwhen.go
- internal/actor/enum_certificateprovidercarryoutby.go
- internal/actor/enum_certificateproviderrelationship.go
- internal/actor/enum_certificateproviderrelationshiplength.go
- internal/actor/enum_lifesustainingtreatment.go
- internal/actor/enum_lpatype.go
- internal/actor/enum_paymenttask.go
- internal/actor/enum_permission.go
- internal/actor/enum_replacementattorneysstepin.go
- internal/actor/enum_status.go
- internal/actor/enum_yesnomaybe.go
- internal/form/enum_yesno.go
- internal/localize/enum_lang.go
- internal/pay/enum_evidencedelivery.go
- internal/pay/enum_feetype.go
- internal/pay/enum_previousfee.go
I'm going to need this when reading from the lpa store, so may as well separate the mess
> MLPAB-1554 Generate UnmarshalText methods for enums

- cypress/e2e/supporter/donor-access.cy.js
- internal/app/dashboard_store.go
- internal/app/dashboard_store_test.go
- internal/app/donor_store.go
- internal/app/donor_store_test.go
- internal/page/fixtures/attorney.go
- internal/page/fixtures/supporter.go
- internal/page/supporter/donor_access.go
- internal/page/supporter/donor_access_test.go
- internal/page/supporter/mock_DonorStore_test.go
- internal/page/supporter/register.go
- lang/cy.json
- lang/en.json
- web/template/supporter/view_lpa.gohtml
> MLPAB-2003: Add remove donor access to supporter LPA

- lang/cy.json
- lang/en.json
- web/template/donor/task_list.gohtml
> MLPAB-2005: Add cy for added

- .github/workflows/terraform_environment_job.yml
- .github/workflows/workflow_destroy_pr_environment.yml
- .github/workflows/workflow_terraform_environment_cleanup.yml
> Update workspace mananger

- internal/page/app_data.go
- internal/page/app_data_test.go
- internal/page/donor/mock_test.go
- internal/page/donor/register.go
- internal/page/donor/register_test.go
- internal/page/donor/task_list.go
- internal/page/donor/task_list_test.go
- internal/page/donor/your_details.go
- internal/page/supporter/delete_organisation.go
- internal/page/supporter/edit_member_test.go
- internal/page/supporter/mock_test.go
- internal/page/supporter/register.go
- internal/page/supporter/register_test.go
- web/template/donor/task_list.gohtml
- web/template/donor/your_details.gohtml
- web/template/layout/donor-lpa-progress.gohtml
- web/template/layout/login-header.gohtml
- web/template/layout/supporter-lpa-context.gohtml
- web/template/supporter/delete_organisation.gohtml
> MLPAB-2024: Move supporter specific data from AppData to AppData.SupporterData

- internal/page/fixtures/attorney.go
- internal/page/fixtures/donor.go
- internal/page/fixtures/supporter.go
For some reason I forgot to put this check on the others...
> Only send to lpa-store in fixtures if signed

- web/template/donor/how_should_attorneys_make_decisions.gohtml
- web/template/donor/how_should_replacement_attorneys_make_decisions.gohtml
- web/template/donor/how_should_replacement_attorneys_step_in.gohtml
- web/template/donor/how_would_certificate_provider_prefer_to_carry_out_their_role.gohtml
You couldn't tell on the longer ones as they forced it to render full width, but the HTML wasn't nested correctly so maybe they would look wrong in the future.
> MLPAB-2021 Move conditional elements to same level as the item

- internal/actor/donor.go
- internal/actor/donor_provided.go
- internal/actor/donor_provided_test.go
- internal/lpastore/client_test.go
- internal/lpastore/lpa.go
- internal/lpastore/lpa_test.go
- internal/page/donor/your_preferred_language.go
- internal/page/donor/your_preferred_language_test.go
- internal/page/fixtures/donor.go
- internal/page/fixtures/fixtures.go
- web/template/layout/donor-details.gohtml
Also moves the field from the Lpa to Donor, where it should be
> MLPAB-2038 Send donor contact language preference to lpa-store

- terraform/account/opensearch_ingestion_service_role.tf
Create service linked role
Fixes MLPAB-2051
> MLPAB-2051 - Create service role for ingestion pipelines

- .github/workflows/detect_changes_to_app_job.yml
- cypress/e2e/attorney/language-preferences.cy.js
- cypress/e2e/attorney/trust-corporation.cy.js
- cypress/e2e/certificate-provider/enter-reference-number.cy.js
- cypress/e2e/donor/confirm-your-identity-and-sign.cy.js
- cypress/e2e/donor/signing-on-behalf.cy.js
- cypress/e2e/supporter/start.cy.js
[it was me :facepalm:](https://github.com/ministryofjustice/opg-mock-onelogin/commit/b8375f8a1aa81dc71045b53a4f5c9560e06249e8#diff-0623bffe86c4076581046d1811b22a8a200fa7c6293b83d76407d1a1b4b3068cR96)
> MLPAB-2050 Unskip the cypress tests

- internal/app/donor_store.go
- internal/app/donor_store_test.go
- internal/app/mock_SearchClient_test.go
- internal/app/uid_store.go
- internal/app/uid_store_test.go
- internal/page/fixtures/supporter.go
- internal/search/client.go
- internal/search/client_test.go
- terraform/environment/variables.tf
Reverts ministryofjustice/opg-modernising-lpa#1214
> Revert "MLPAB-2059 Index full record with app and change queries to work"

- internal/lpastore/client_test.go
- internal/lpastore/lpa.go
- internal/lpastore/lpa_test.go
This will allow us differentiate between LPAs created through MRLPA and through scanning.
It's always "online".
Plenty: it's my first proper contribution to this repo! But it was all very straightforward, thank you
> Add LPA channel to data sent to LPA Store

- internal/page/donor/choose_attorneys.go
- internal/page/donor/choose_attorneys_test.go
- internal/page/donor/choose_replacement_attorneys.go
- internal/page/donor/choose_replacement_attorneys_test.go
- web/template/donor/choose_attorneys.gohtml
- web/template/donor/choose_replacement_attorneys.gohtml
> MLPAB-2023: Limit trust corporation appointment

- Makefile
I noticed we had some drift with key structures here while testing out share codes.
> Update SK drift in make commands

- .github/workflows/workflow_path_to_live.yml
Fix missing input for demo deploy
> fix demo deploy

- .github/workflows/terraform_account_job.yml
- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
- terraform/account/.envrc
- terraform/account/.terraform.lock.hcl
- terraform/account/iam_sns_feedback_role.tf
- terraform/account/opensearch.tf
- terraform/account/terraform.tf
- terraform/account/terraform.tfvars.json
- terraform/account/variables.tf
- terraform/account/versions.tf
Share a single collection to reduce costs
Fixes MLPAB-2029
- Create an account level collection
> MLPAB-2029 - create an account level opensearch serverless collection

- terraform/account/opensearch.tf
Make space for new policies.
Fixes MLPAB-2029
- Namespace policies
> MLPAB-2029 - namespace policies for shared

- docs/architecture/dsl/local/makeRegisterSoftwareSystem.dsl
- docs/architecture/dsl/local/structurizr-Container-001.mmd
- docs/architecture/dsl/local/structurizr-SystemContext.mmd
- docs/architecture/dsl/local/workspace.dsl
update diagrams for clarity and accuracy. [MLPAB-2101](https://opgtransform.atlassian.net/browse/MLPAB-2101)
[MLPAB-2101]: https://opgtransform.atlassian.net/browse/MLPAB-2101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update diagrams. Remove yoti. Update labels for clarity.

- cypress/smoke/smoke.cy.js
I missed this timeout when setting the others, so maybe it will help
> Increase pageLoadTimeout for smoke test

- .github/workflows/workflow_destroy_pr_environment.yml
need lambda zips before cleanup
Fixes MLPAB-2167
> MLPAB-2167 - checkout before download

- internal/app/app.go
- internal/app/attorney_store.go
- internal/app/attorney_store_test.go
- internal/app/certificate_provider_store.go
- internal/app/certificate_provider_store_test.go
- internal/dynamo/client.go
- internal/dynamo/client_test.go
- internal/page/certificateprovider/enter_reference_number.go
- internal/page/certificateprovider/enter_reference_number_test.go
- internal/page/certificateprovider/mock_CertificateProviderStore_test.go
- internal/page/certificateprovider/register.go
- internal/page/fixtures/attorney.go
- internal/page/fixtures/certificate_provider.go
- internal/page/fixtures/dashboard.go
- internal/page/fixtures/donor.go
- internal/page/fixtures/fixtures.go
- terraform/account/opensearch.tf
> MLPAB-2127: Resequence certificate provider enter reference number for fault tolerance

- terraform/environment/data_sources.tf
- terraform/environment/opensearch.tf
- terraform/environment/opensearch_ingestion_pipeline.tf
- terraform/environment/regions.tf
Reduce cost and build time by sharing a collection in each account
Fixes MLPAB-2165
- use the shared opensearch collection
> MLPAB-2165 move environments over to the account level opensearch collection

- cmd/event-received/makeregister_event_handler_test.go
- cmd/event-received/sirius_event_handler_test.go
> MLPAB-1973: Event name regression tests

- terraform/environment/refactor.tf
> correct typo in moved block

- terraform/account/opensearch.tf
Ensure policy name is unique and under 32 characters
> MLPAB-2185 - Fix name of policy

- terraform/account/region/dynamodb_exports_s3_bucket.tf
- terraform/account/region/modules/dynamodb_exports_s3_bucket/main.tf
- terraform/account/region/modules/dynamodb_exports_s3_bucket/variables.tf
- terraform/account/region/variables.tf
- terraform/account/regions.tf
Manage who can encrypt/decrypt objects
Fixes MLPAB-2200
- use customer managed key for bucket encryption
> MLPAB-2200 - enable CMK on dynamodb exports bucket

- .github/workflows/workflow_destroy_pr_environment.yml
Destroy PR env job always returns an error when deleting the index
Fixes MLPAB-2239
- Fix handling of error
> MLPAB-2239 - fix error handling in delete index steps

- .github/workflows/workflow_destroy_pr_environment.yml
- .github/workflows/workflow_pr.yml
Delete index job fails on Github Actions
Fixes MLPAB-2239
- add space in conditional statement
> MLPAB-2239 - fix index delete step

- cypress/e2e/donor/check-your-details.cy.js
- cypress/e2e/donor/confirm-your-identity-and-sign.cy.js
- internal/page/donor/register.go
- internal/page/donor/register_test.go
- internal/page/donor/register_with_court_of_protection.go
- internal/page/donor/register_with_court_of_protection_test.go
- internal/page/donor/task_list.go
- internal/page/donor/task_list_test.go
- internal/page/fixtures/attorney.go
- internal/page/fixtures/certificate_provider.go
- internal/page/fixtures/dashboard.go
- internal/page/fixtures/donor.go
- internal/page/fixtures/fixtures.go
- internal/page/fixtures/supporter.go
- internal/page/paths.go
- lang/cy.json
- lang/en.json
- web/template/certificate_provider_fixtures.gohtml
- web/template/donor/onelogin_identity_details.gohtml
- web/template/donor/we_have_contacted_voucher.gohtml
- web/template/donor/withdraw_this_lpa.gohtml
- web/template/fixtures.gohtml
> MLPAB-2270: Fix dev review issues, persist GOL email on Donor if not set

- terraform/environment/terraform.tfvars.json
To support indexing via opensearch ingestion pipeline.
Fixes MLPAB-2277
> MLPAB-2277: Re-enable dynamodb streams

- terraform/account/terraform.tf
- terraform/environment/terraform.tf
Apply principle of least privilege to state access
Fixes MLPAB-2276
- use new limited state role
- https://developer.hashicorp.com/terraform/language/settings/backends/s3
> MLPAB-2276 - don't use ci role for state access

- go.mod
- internal/page/certificateprovider/confirm_dont_want_to_be_certificate_provider.go
- internal/page/certificateprovider/confirm_dont_want_to_be_certificate_provider_test.go
- internal/page/certificateprovider/confirm_your_details.go
- internal/page/certificateprovider/confirm_your_details_test.go
- internal/page/certificateprovider/enter_date_of_birth.go
- internal/page/certificateprovider/enter_date_of_birth_test.go
- internal/page/certificateprovider/guidance.go
- internal/page/certificateprovider/guidance_test.go
- internal/page/certificateprovider/identity_with_one_login.go
- internal/page/certificateprovider/identity_with_one_login_callback.go
- internal/page/certificateprovider/identity_with_one_login_callback_test.go
- internal/page/certificateprovider/identity_with_one_login_test.go
- internal/page/certificateprovider/one_login_identity_details.go
- internal/page/certificateprovider/one_login_identity_details_test.go
- internal/page/certificateprovider/provide_certificate.go
- internal/page/certificateprovider/provide_certificate_test.go
- internal/page/certificateprovider/read_the_lpa.go
- internal/page/certificateprovider/read_the_lpa_test.go
- internal/page/certificateprovider/register.go
- internal/page/certificateprovider/register_test.go
- internal/page/certificateprovider/task_list.go
- internal/page/certificateprovider/task_list_test.go
- internal/page/certificateprovider/unable_to_confirm_identity.go
- internal/page/certificateprovider/unable_to_confirm_identity_test.go
- internal/page/certificateprovider/what_is_your_home_address.go
- internal/page/certificateprovider/what_is_your_home_address_test.go
- internal/page/certificateprovider/your_preferred_language.go
- internal/page/certificateprovider/your_preferred_language_test.go
> Pass certificate provider into handlers

- .jira/config.yml
Map deployments in jira
Fixes MLPAB-1943
- https://github.com/atlassian/github-for-jira/blob/main/docs/deployments.md#environment-mapping
> MLPAB0-1943 - map environments for Jira

- terraform/environment/terraform.tfvars.json
User research requires an env with and without a onelogin mock
Fixes MLPAB-2474
- define a ur2
> MLPAB-2474 - create ur2 env

- terraform/account/region/modules/antivirus_definitions/s3.tf
- terraform/account/region/modules/s3_batch_manifests/s3.tf
Previous job failed due to missing provider (the configuration attempted to create the resources in the identity account)
Fixes MLPAB-2499
> MLPAB-2499 - fix providers

- terraform/environment/terraform.tfvars.json
avoid the need to use allow listed emails and phone numbers during ITHC
> MLPAB-2511 - use live notify on preproduction

- terraform/account/region/modules/antivirus_definitions/s3.tf
- terraform/account/region/modules/dynamodb_exports_s3_bucket/main.tf
- terraform/account/region/modules/s3_batch_manifests/s3.tf
- terraform/account/region/s3_lb_access_logs.tf
Use lifecycles to abort MPUs
Fixes MLPAB-2499
- add lifecycle to exports bucket
- add lifecycle to load-balancer logs bucket
> MLPAB-2499 apply to remaining buckets

- terraform/environment/region/modules/mock_onelogin/ecs.tf
So we have one less thing to click.
Fixes MLPAB-2518
> MLPAB-2518: Default to random sub in deployed mock GOL

- terraform/environment/terraform.tfvars.json
Re-enable WAF
Fixes MLPAB-2543
> MLPAB-2543 - enable WAF on preproduction

- lambda/create_s3_replication_job/Dockerfile
Update the alpine version used in the image
> Bump alpine version

- renovate.json
incorrect reference to the package
Fixes MLPAB-2557
- use module source as reference
- fix renovate config warning about `prPriority` in config `major`
> fix dep reference

- terraform/environment/region/modules/schedule_runner/lambda.tf
> Namespace scheduler name to env and region

- terraform/account/kms_key_sqs.tf
Reverts ministryofjustice/opg-modernising-lpa#1566
> Revert "MLPAB-2567 Allow lambda to use sqs key"

- internal/sesh/dynamo_store.go
- web/template/layout/print-this-page.gohtml
I don't have an iOS device to try this on, but it did stop it announcing as a group on Mac Safari so maybe it will work?
> MLPAB-2462 Add role=img to printer icon

- cypress/e2e/donor/check-you-can-sign.cy.js
- internal/donor/donorpage/check_you_can_sign.go
- web/template/donor/check_you_can_sign.gohtml
Just spotted that I messed up this template name, and added a test so we'd spot problems in the future
> Fix template name for Check you can sign page

- terraform/account/kms_key_event_recieved_sqs.tf
The KMS CMK does not have the correct permissions applied as defined in terraform. Recreating and extending permissions with explicit statements should do the trick
Fixes MLPAB-2613
- fix key name and replace to ensure correct policy is attached
- fix statements for services and user
- allow iam users
> MLPAB-2613 - Fix event received SQS KMC CMK permissions

- internal/donor/donordata/certificate_provider.go
- internal/donor/donordata/independent_witness.go
- internal/donor/donordata/provided.go
- internal/donor/donordata/provided_test.go
Comment on ticket says to prevent changing on other pages, but that will happen in https://opgtransform.atlassian.net/browse/MLPAB-2610 so I've not done anything special here
> MLPAB-2724 Allow changing witness code mobile number after signing

- lang/cy.json
- lang/en.json
> MLPAB-2820: Add missing evidence title translation

- docker/docker-compose.dev.yml
- internal/donor/donorpage/progress.go
- internal/donor/donorpage/progress_test.go
Its more verbose but to me it feels easier to parse the logic behind each notification now
Fixes MLPAB-2829
> MLPAB-2829: Flatten progress notifications conditions

- internal/donor/donorpage/delete_lpa.go
- internal/donor/donorpage/delete_lpa_test.go
- internal/donor/donorpage/register.go
- internal/donor/donorpage/withdraw_lpa.go
- internal/donor/donorpage/withdraw_lpa_test.go
- internal/notify/email.go
- internal/page/fixtures/donor.go
> MLPAB-1673: Inform certificate provider when donor deletes or withdraws LPA

- .codecov.yml
- Makefile
- cmd/event-logger/event_sender.go
- cmd/event-logger/main.go
- cypress/e2e/donor/progress.cy.js
- cypress/support/commands.js
- internal/page/fixtures/donor.go
> MLPAB-2830:  Add sirius event emitting to event-logger

- docker/create-s3-replication-job/Dockerfile
- docker/event-received/Dockerfile
- docker/schedule-runner/Dockerfile
- docker/scheduled-task-adder/Dockerfile
> MLPAB-2574: Bump lambda images

- web/assets/scss/patterns/_progress_bar.scss
- web/template/attorney/progress.gohtml
- web/template/layout/donor-lpa-progress.gohtml
> MLPAB-2753: Remove bold from next step in progress trackers

- terraform/account/region/load_balancer_access_logs_athena.tf
- terraform/account/region/variables.tf
- terraform/account/regions.tf
- terraform/account/terraform.tfvars.json
- terraform/account/variables.tf
Only create Athena resources when we need them
Fixes MLPAB-2844
- conditionally create athena resources
> MLPAB-2844 - conditionally create athena resources

- Makefile
- cmd/event-logger/event_sender.go
- cmd/event-logger/main.go
- cypress/e2e/donor/confirm-your-identity.cy.js
- cypress/e2e/donor/progress.cy.js
- cypress/e2e/donor/what-you-can-do-now.cy.js
- internal/donor/donordata/provided.go
- internal/donor/donordata/provided_test.go
- internal/donor/donorpage/task_list.go
- internal/donor/donorpage/task_list_test.go
- internal/donor/donorpage/what_you_can_do_now.go
- internal/donor/donorpage/what_you_can_do_now_expired.go
- internal/donor/donorpage/what_you_can_do_now_expired_test.go
- internal/donor/donorpage/what_you_can_do_now_test.go
- internal/donor/path_test.go
- internal/donor/store.go
- internal/donor/store_test.go
- internal/page/fixtures/donor.go
- internal/voucher/voucherpage/register.go
- internal/voucher/voucherpage/verify_donor_details.go
- internal/voucher/voucherpage/verify_donor_details_test.go
- internal/voucher/voucherpage/vouch_failer_test.go
- web/template/donor/what_you_can_do_now.gohtml
- web/template/donor/what_you_can_do_now_expired.gohtml
- web/template/donor/your_details.gohtml
> MLPAB-2759: Use donor identity verification as vouch attempt

- cmd/event-received/main.go
- cmd/mlpa/main.go
- docker/docker-compose.yml
- docker/localstack/localstack-init.sh
- internal/s3/client.go
- internal/s3/client_test.go
- terraform/environment/region/modules/app/ecs.tf
> MLPAB-2615: Use KMS key alias when putting to S3

- .github/workflows/on_path_to_live_failure.yml
- .github/workflows/slack_job.yml
An update to the slack notifications action we use changed the payload requirements
- conform to new requirements for slack action
- https://github.com/slackapi/slack-github-action
> fix notifications for ptl failures

- internal/document/store.go
- internal/donor/donorpage/send_us_your_evidence_by_post.go
- internal/event/events.go
- internal/event/events_test.go
- internal/event/testdata/reduced-fee-requested.json
https://github.com/ministryofjustice/opg-event-store/pull/132
> MLPAB-2879 Add previous fee info to reduced-fee-requested

- lang/cy.json
- lang/en.json
- web/template/donor/task_list.gohtml
> MLPAB-2782: Update tasklist help details component content

- internal/page/guidance.go
- internal/page/guidance_test.go
- internal/templatefn/fn.go
- internal/templatefn/fn_test.go
- lang/cy.json
- lang/en.json
- web/assets/scss/patterns/_service_header.scss
- web/template/guidance/glossary.gohtml
- web/template/layout/login-header.gohtml
> MLPAB-2874: Add opens in new tab to help and support nav

- cypress/e2e/donor/progress.cy.js
- cypress/e2e/donor/what-you-can-do-now.cy.js
- internal/donor/donorpage/register.go
- internal/donor/donorpage/what_you_can_do_now.go
- internal/donor/donorpage/what_you_can_do_now_expired.go
- internal/donor/donorpage/what_you_can_do_now_expired_test.go
- internal/donor/donorpage/what_you_can_do_now_test.go
- internal/page/fixtures/donor.go
- internal/voucher/voucherpage/task_list.go
- internal/voucher/voucherpage/task_list_test.go
- lang/cy.json
- lang/en.json
- web/template/donor/we_have_contacted_voucher.gohtml
- web/template/donor/what_you_can_do_now.gohtml
- web/template/donor/what_you_can_do_now_expired.gohtml
> MLPAB-2871: Vary what happens next content by vouch status

- cypress/e2e/attorney/trust-corporation.cy.js
- cypress/e2e/certificate-provider/confirm-your-identity.cy.js
- cypress/e2e/certificate-provider/enter-reference-number.cy.js
- cypress/e2e/donor/lpa-type.cy.js
- cypress/e2e/voucher/enter-reference-number.cy.js
I should remember never to change too much...
> Update tests for new mock-onelogin

- cypress/support/commands.js
- internal/attorney/attorneypage/enter_reference_number.go
- internal/attorney/attorneypage/enter_reference_number_test.go
- internal/attorney/attorneypage/mock_LpaStoreClient_test.go
- internal/attorney/attorneypage/mock_test.go
- internal/attorney/attorneypage/register.go
- internal/dashboard/dashboarddata/results.go
- internal/dashboard/store.go
- internal/dashboard/store_test.go
- internal/lpastore/update.go
- internal/lpastore/update_test.go
- internal/page/fixtures/attorney.go
- web/template/attorney_fixtures.gohtml
- web/template/dashboard.gohtml
> MLPAB-2878: Send email to LPA store when paper attorney accesses online

- cmd/mlpa/main.go
- docker/docker-compose.yml
- go.sum
- internal/app/app.go
- internal/app/app_test.go
- internal/donor/witness_code_sender.go
- internal/donor/witness_code_sender_test.go
- internal/page/fixtures/donor.go
- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
> MLPAB-2986: Default to test witness code on non-prod environments

- .github/workflows/schedule_update_opg_metrics_credentials.yml
There is a copy error in the targeted apply
- fix target address
> fix target for metrics event connection

- go.sum
- internal/donor/donorpage/are_you_applying_for_fee_discount_or_exemption.go
- internal/donor/donorpage/are_you_applying_for_fee_discount_or_exemption_test.go
> MLPAB-2973: Set payment type to FullFee when set to other value

- web/template/layout/contextual-lpa.gohtml
> MLPAB-2940: Reference independent witness phone rather than mobile

- cmd/event-received/sirius_event_handler.go
- cmd/event-received/sirius_event_handler_test.go
> MLPAB-2932: Ignore donor-submission-completed when donor is online

- internal/page/fixtures/attorney.go
> MLPAB-2986: Fix attorney fixtures when paper attorney has signed

- terraform/environment/terraform.tfvars.json
> MLPAB-3013: Disable mock pay for UR

- internal/localize/localizer.go
- internal/localize/localizer_test.go
> MLPAB-3014: Default to London when displaying time and dateTime

- package.json
- web/assets/main.js
- yarn.lock
> MLPAB-3020: Remove jquery

- docker/event-received/.trivyignore.yaml
- docker/event-received/Dockerfile
> Libxmlpatch

- docker/create-s3-replication-job/.trivyignore.yaml
- docker/create-s3-replication-job/Dockerfile
- docker/event-received/.trivyignore.yaml
Patch libxml/sqlite in s3 replication
> Patch libxml/sqlite in s3 replication

- terraform/account/variables.tf
A new tag is required for AWS resources
Fixes MLPAB-2850
- add service-area tag
> MLPAB-2850 - update default tags to include service-area - account level

- .github/workflows/tags_job.yml
- cypress/e2e/attorney/dashboard.cy.js
- internal/attorney/store.go
- internal/attorney/store_test.go
- internal/dashboard/dashboarddata/results.go
- internal/dashboard/store.go
- internal/dashboard/store_test.go
- internal/lpastore/lpadata/lpa.go
- internal/page/fixtures/attorney.go
- package.json
- web/template/dashboard.gohtml
> MLPAB-3059: Handle trust corporations and replacements on dashboard view

- terraform/environment/variables.tf
A new tag is required for AWS resources
Fixes MLPAB-2850
- add service-area tag
> MLPAB-2850 - update default tags to include service-area - environment level

- .github/workflows/curl_health_checks.yml
- .github/workflows/dispatch_deploy_to_ur_environment.yml
UI tests are not the most useful in this use case
Fixes MLPAB-3133
- create a test of the health checks
- run health check tests when deploying to ur
> MLPAB-3133 -  run a curl smoke test instead of cypress UI tests for ur deploy

- .github/workflows/go-integration-tests.yml
- .github/workflows/workflow_merge_group.yml
- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
- Makefile
- internal/dynamo/client_integration_test.go
I wanted to prove that `Create` and `CreateOnly` were the same. Then thought I may as well extend to other things too, although this is not exhaustive yet, I left the methods that require indexes for another day and it is only happyish paths.
> MLPAB-2173 Add some dynamo integration tests

- internal/page/fixtures/attorney.go
- internal/page/fixtures/certificate_provider.go
- internal/page/fixtures/donor.go
- internal/page/fixtures/fixtures.go
- internal/page/fixtures/supporter.go
- web/template/attorney_fixtures.gohtml
- web/template/certificate_provider_fixtures.gohtml
- web/template/fixtures.gohtml
Fixes MLPAB-3131, Fixes MLPAB-3081.
I had to reintroduce a wait for the real UID to come through, as we were landing on make or add an LPA without the nav to get to dashboard.
> MLPAB-3131, MLPAB-3081: Select real UID from UI and set restrictions appropriately

- cypress/smoke/smoke.cy.js
this worked locally against preproduction, so hopefully it will actually work when merged
> MLPAB-3010 Accept terms if present in smoke test

- terraform/account/kms_key_athena_s3.tf
- terraform/account/region/load_balancer_access_logs_athena.tf
- terraform/account/region/variables.tf
- terraform/account/regions.tf
Use CMK and versioning on Athena S3 bucket
Fixes MLPAB-3030
- Set up bucket versioning 
- Use CMK for encryption
- https://docs.aws.amazon.com/athena/latest/ug/encryption.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_versioning
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_server_side_encryption_configuration
> MLPAB-3030 - Athena encryption and bucket versioning

- terraform/environment/cloudwatch_dashboards/security.json.tftpl
- terraform/environment/region/cloudwatch_dashboards.tf
- terraform/environment/region/network.tf
Make security sensitive areas visible
Fixes MLPAB-3184
- create security dashboard with a templatefile()
- Rename health dashboard
- https://developer.hashicorp.com/terraform/language/functions/templatefile
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_dashboard
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/nat_gateways
> MLPAB-3184 - create a dashboard for security monitoring

- cypress/e2e/certificate-provider/provide-certificate.cy.js
- internal/donor/donorpage/certificate_provider_details_test.go
- internal/donor/donorpage/how_would_certificate_provider_prefer_to_carry_out_their_role.go
- internal/donor/donorpage/how_would_certificate_provider_prefer_to_carry_out_their_role_test.go
- internal/donor/donorpage/register.go
- internal/donor/mock_test.go
> MLPAB-1567 Re-send certificate provider invite email if changed prior to signing or use

- internal/lpastore/client_test.go
I missed this the first time around 🤦 
Fixes MLPAB-3187.
> MLPAB-3187: Include company number in trust corporation sign pact test

- .github/workflows/dispatch_manage_public_access_ur_environment.yml
- terraform/environment/.terraform.lock.hcl
- terraform/environment/global/mainstream_content_ecs_task_roles.tf
- terraform/environment/global/outputs.tf
- terraform/environment/region/dns.tf
- terraform/environment/region/ecs.tf
- terraform/environment/region/modules/app/access_logging_bucket.tf
- terraform/environment/region/modules/app/data_sources.tf
- terraform/environment/region/modules/mainstream_content/alb.tf
- terraform/environment/region/modules/mainstream_content/data_sources.tf
- terraform/environment/region/modules/mainstream_content/ecs.tf
- terraform/environment/region/modules/mainstream_content/outputs.tf
- terraform/environment/region/modules/mainstream_content/variables.tf
- terraform/environment/region/modules/mainstream_content/versions.tf
- terraform/environment/region/modules/mainstream_content/waf.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Fixes MLPAB-##
- Create IAM role for ECS task
- Deploy ECS task
- Create Certificates
- Add DNS
- point content to correct environment
- enable public access to ur mainstream content
> MLPAB-3211 - move mainstream content to this repo

- internal/donor/donordata/provided.go
- internal/donor/donordata/voucher.go
- internal/donor/donorpage/confirm_person_allowed_to_vouch.go
- internal/donor/donorpage/enter_voucher.go
- internal/donor/donorpage/identity_details.go
- internal/donor/donorpage/warning_interruption.go
- internal/donor/donorpage/your_address.go
- internal/identity/user_data.go
- internal/names/equal.go
- internal/names/equal_test.go
- internal/place/address.go
- internal/place/address_test.go
- internal/voucher/voucherdata/provided.go
- internal/voucher/voucherpage/confirm_allowed_to_vouch.go
Also adds a similar change for address matching
> MLPAB-3305 Normalise capitalisation and hyphenation when matching names
