- .github/workflows/go-unit-tests.yml
- app/internal/fake/fake.go
- app/internal/fake/fake_test.go
- app/main.go
After #5 and #7 we were still getting an error in codecov advising that there was an empty coverage report. This PR ensures we are getting (mostly) the expected coverage for our Go app.
Fixes MLPAB-12
It appears that codecov doesn't recognise `main.go` or anything in the `main` package as requiring a coverage figure. As soon as I added a dummy package the coverage stats were recognised. Depending on how logic-heavy our main function is we may need to delve further into why `main` code is ignored but for now we can confirm any other code will be included in our coverage stats.
Once we play the first ticket that involves writing some Go code (and a test) we can drop the `fake` package and test added in this PR.
> MLAPB-23: Fix empty coverage report in codecov

- terraform/account/.terraform.lock.hcl
- terraform/account/kms.tf
- terraform/account/terraform.tf
- terraform/account/variables.tf
Create a encryption key per account for log encryption
Fixes MLPAB-63
- Add a global aws provider for IAM
- Create a multi-region kms key
- add data sources to retrieve useful attributes for interpolating ARNs
- https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html
> MLPAB-63 -  Create a encryption key per account for log encryption

- terraform/account/region/certificate.tf
- terraform/account/region/terraform.tf
- terraform/account/regions.tf
- terraform/account/terraform.tf
Encrypt traffic down to load balancers
Fixes MLPAB-64 MLPAB-65
- Create AWS ACM certificate for app
- Create providers for management
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate#referencing-domain_validation_options-with-for_each-based-resources
> MLPA-65 - Create certificate for app ALB

- Dockerfile.dev
- docker-compose.override.yml
Enables a watch on the go app so the binary is automatically rebuilt when valid changes are made.
Fixes MLPAB-87
> MLAPB-87: Add air auto-reload to dev

- terraform/environment/region/modules/app/ecs.tf
Start the implementation of observability with xRay
Fixes MLPAB-82
- Add write permissions for using the X-Ray daemon, AWS CLI, or AWS SDK to upload segment documents and telemetry to the X-Ray API
- https://docs.aws.amazon.com/xray/latest/devguide/security_iam_id-based-policy-examples.html
> MLPAB-82 - Add permissions for app ECS to put telemetry to xray

- .github/workflows/tags_job.yml
- .pre-commit-config.yaml
- renovate.json
- terraform/environment/region/modules/app/ecs.tf
The newer version of the action runs into issues creating new tags frequently
Fixes MLPAB-129
- Set version to 1.36.0
- ignore dependency for now
- fix issue with access to cookie secret
> MLPAB-129 - rollback version of github-tag-action

- terraform/environment/region/modules/app/alb.tf
Health-checks are currently failing for receiving a non-200 response
Fixes MLPAB-149
- Configure ALP target group health-check to use /start
A reminder that health-checks are being performed inside the network, so only the redirect from / to /start was causing an issue, not any of the protocol or port redirects performed by the load-balancer listener rules.
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html
* ~I have run an accessibility tool on any pages I have made changes to …
> MLPAB-149 - Bug - Configure healthcheck to hit /start

- terraform/account/backup_vaults.tf
- terraform/account/refactoring.tf
- terraform/account/region/backup_vault.tf
Prepare for backups to be copied to a second region
Fixes MLPAB-####
- move first region backup vault out of the region module to the "global" level
- create a vault for the second region
- https://www.terraform.io/language/modules/develop/refactoring
* ~I have run an accessibility tool on any pages I have made changes to and fixed any ~issues found
> MLPAB-154 - Create backup vaults in both regions

- terraform/environment/.terraform.lock.hcl
- terraform/environment/backup_plan.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Fixes MLPAB-151
- pull vaults for both regions and backup role
- create a backup plan
- add variable to enable copy action to a second region
- associate resources that are to be backed up
- add a variable to enable backups
- add notifications to AWS SNS (temporary) for backup and copy failures
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_plan
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_selection
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/backup_vault_notifications
- https://docs.aws.amazon.com/aws-backup/latest/devguide/sns-notifications.html
- …
> MLPAB-151 - Create a backup plan for DynamoDB tables

- .github/workflows/workflow_destroy_pr_environment.yml
New Destroy PR env on merge workflow failed to start destroy
Fixes MLPAB-148
- insert a terraform init step
> MLPAB-148 - Fix - When destroying a PR environment, init before destroy

- app/web/template/about_payment.gohtml
Merged before the UI tests had finished - this ensures we have an anchor element rather than a button.
> Fix MLPAB-135

- .github/workflows/workflow_pr.yml
- terraform/environment/dynamodb.tf
- terraform/environment/region/modules/app/ecs.tf
Using AWS managed keys does not allow for fine grained control
Fixes MLPAB-158
- allow ECS to use DynamoDB encryption key
- use CMK for DynamoDB server side encryption
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/encryption.howitworks.html#managed-key-customer-managed
-https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#server_side_encryption
* ~The product team have …
> MLPAB-158 - Use CMK for DynamoDB encryption

- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
Simplify the input variables by passing the role rather than the id and arn separately
Fixes MLPAB-152
- Use a type of any for the ecs_execution_role variable
- provide the whole role as an input
- Also fix policy statements in task role for encryption and decryption access
- https://www.terraform.io/language/values/variables#type-constraints
> MLPAB-152 - Pass the execution role as a single object rather than attributes

- terraform/account/regions.tf
- terraform/account/terraform.tfvars.json
- terraform/account/variables.tf
We want to be ready to deploy to a second region
Fixes MLPAB-254
- Add an input variable to define regions we should deploy to
- Define eu-west-1 as a region we deploy to
- Define a second region instance of the region module (without requiring the deployment there)
* ~The product team have tested …
> MLPAB-254 - Manage account configuration for second region

- docs/runbooks/deployment_into_additional_regions.md
- terraform/environment/config_file.tf
- terraform/environment/dns.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
We want to be ready to deploy to a second region
Fixes MLPAB-255
- Add an input variable to define regions we should deploy to
- Define eu-west-1 as a region we deploy to
- Define a second region instance of the region module (without requiring the deployment there)
- Add run-book explaining second region procedure
- https://www.terraform.io/language/modules/develop/refactoring#moved-block-syntax
* ~The product team have tested …
> MLPAB-255 - Manage environment configuration for second region

- terraform/account/cloudwatch_kms.tf
- terraform/account/dynamodb_kms.tf
- terraform/account/secrets_manager_kms.tf
Fix issue of alarms raised for unauthorised actions that should be permitted.
```
User: access-analyzer is not authorized to perform: kms:ListGrants on resource: arn:aws:kms:::key/ because no resource-based policy allows the kms:ListGrants action
```
Fixes MLPAB-269
- Allow list actions generally
- https://docs.aws.amazon.com/service-authorization/latest/reference/list_awskeymanagementservice.html
* ~The product team have tested …
> allow kms list permissions generally

- terraform/account/.terraform.lock.hcl
- terraform/account/sns_kms.tf
AWS SNS topics should be encrypted with a customer managed MKS key
Fixes MLPAB-153
- Create a CMK for AWS SNS
- allow backup role to use it for encryption 
- Allow SNS service to use it for decryption
- https://aws.amazon.com/blogs/compute/encrypting-messages-published-to-amazon-sns-with-aws-kms/
> MLPAB-153 - Create CMK for SNS

- terraform/environment/region/modules/app/ecs.tf
Enabling this option reduces security attack vectors since the container instance’s filesystem cannot be tampered with or written to unless it has explicit read-write permissions on its filesystem folder and directories. This control also adheres to the principle of least privilege.
Fixes MLPAB-275
- Set `readonlyRootFilesystem` to true in container definition
- https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ecs-5-remediation
> MLPAB-275 - Enable readonly root filesystem as per FSBP ECS.5

- terraform/account/dynamodb_kms.tf
Allow Breakglass role to view DynamoDB data
Fixes MLPAB-299
- Add a new statement to the DynamoDB KMS key allowing breakglass to `kms:Decrypt`
> MLPAB-299 - Add decrypt permissions for breakglass role on Production

- terraform/account/region/network.tf
All subnets have an attribute that determines whether a network interface created in the subnet automatically receives a public IPv4 address. Instances that are launched into subnets that have this attribute enabled have a public IP address assigned to their primary network interface.
Fixes MLPAB-281
- don't assign public IPs in the default subnet of each availability zone
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_subnet
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/availability_zones
- https://www.terraform.io/language/meta-arguments/for_each
> MLPAB-281 - Do not map public IPs on launch of default subnets

- .gitleaks.toml
- .pre-commit-config.yaml
- Makefile
- gitleaks-baseline.json
We're no longer scanning the baseline file with this change which should lead to a slimmer baseline file. I've also added a make command to generate a fresh baseline file for when we accept dummy/false positives in code going forward.
Fixes MLPAB-308
> MLAPB-308: Add gitleaks baseline generator command and ignore baseline

- terraform/account/region/default_vpc.tf
- terraform/account/region/network.tf
Access to remote server administration ports, such as port 22 (SSH) and port 3389 (RDP), should not be publicly accessible, as this may allow unintended access to resources within your VPC.
Fixes MLPAB-310
- move default VPC resource management to it's own file
- Manage the default VPC default network ACL
- Deny ssh and rdp port access on default network acl
- https://www.terraform.io/language/meta-arguments/for_each
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/network_acls
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeNetworkAcls.html
> MLPAB-310 - Deny SSH and RDP access in default VPC default network ACL

- .github/workflows/workflow_destroy_pr_environment.yml
Some environments were not destroyed as early as they could have been.
Fixes MLPAB-311
- remove paths filter from job
> MLPAB-311 - Remove path filtering from destroy pr env job

- terraform/account/region/default_vpc.tf
- terraform/account/region/variables.tf
- terraform/account/regions.tf
With the [VPC Flow Logs](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html) feature, you can capture information about the IP address traffic going to and from network interfaces in your VPC. After you create a flow log, you can view and retrieve its data in CloudWatch Logs.
Security Hub recommends that you enable flow logging for packet rejects for VPCs. Flow logs provide visibility into network traffic that traverses the VPC and can detect anomalous traffic or provide insight during security workflows.
By default, the record includes values for the different components of the IP address flow, including the source, destination, and protocol. For more information and descriptions of the log fields, see VPC Flow Logs in the Amazon VPC User Guide.
Fixes MLPAB-287
- Create flow …
> MLPAB-287 - Create flow logs for the default VPC

- .github/workflows/tags_job.yml
- .github/workflows/terraform_environment_job.yml
- .github/workflows/workflow_destroy_pr_environment.yml
To avoid untrusted logged data to use set-stateand set-output workflow commands without the intention of the workflow author we have introduced a [new set of environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files) to manage state and output.
Fixes MLPAB-320
replace output command with GITHUB_OUTPUT in;
- tags_job.yml
- workflow_destroy_pr_environment.yml
- terraform_environment_job.yml
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> MLPAB-320 - Replace set-output command with GITHUB_OUTPUT

- terraform/account/.terraform.lock.hcl
- terraform/account/region/s3_lb_access_logs.tf
Elastic Load Balancing provides access logs that capture detailed information about requests sent to your load balancer. Each log contains information such as the time the request was received, the client's IP address, latencies, request paths, and server responses. You can use these access logs to analyze traffic patterns and to troubleshoot issues.
Fixes MLPAB-345
- Create an S3 bucket to collect access logs for elastic load balancers
> MLPAB-345 - Create lb access logging bucket

- terraform/account/.terraform.lock.hcl
- terraform/account/region/default_vpc.tf
Access to remote server administration ports, such as port 22 (SSH) and port 3389 (RDP), should not be publicly accessible, as this may allow unintended access to resources within your VPC.
Fixes MLPAB-344
- reorder rule so that the allow traffic rule is after deny traffic rules
- add ipv6_cidr_block to each deny rule
> MLPAB-344 - Update Network ACLs to apply to IPv6 CIDR range

- terraform/account/region/network.tf
Access to remote server administration ports, such as port 22 (SSH) and port 3389 (RDP), should not be publicly accessible, as this may allow unintended access to resources within your VPC.
Fixes MLPAB-344
- upgrade network module
- https://github.com/ministryofjustice/opg-terraform-aws-network
> MLPAB-344 - Upgrade network moduleto add new network ACL rules

- terraform/account/region/network.tf
- terraform/account/region/vpc_endpoints.tf
To improve the security posture of your VPC, you can configure Amazon EC2 to use an interface VPC endpoint. Interface endpoints are powered by AWS PrivateLink, a technology that enables you to access Amazon EC2 API operations privately. It restricts all network traffic between your VPC and Amazon EC2 to the Amazon network. Because endpoints are supported within the same Region only, you cannot create an endpoint between a VPC and a service in a different Region. This prevents unintended Amazon EC2 API calls to other Regions. 
Fixes MLPAB-283
- Create a private vpc endpoint for the application subnets and public subnets
- Create a vpc endpoint policy for ec2 allowing any actions (at present)
- https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html# …
> MLPAB-283 - Create an vpc inteface endpoint for ec2 with policy

- terraform/account/iam_sns_delivery_notifications_role.tf
- terraform/account/iam_sns_feedback_role.tf
Logging is an important part of maintaining the reliability, availability, and performance of services. Logging message delivery status helps provide operational insights, such as the following:
- Knowing whether a message was delivered to the Amazon SNS endpoint.
- Identifying the response sent from the Amazon SNS endpoint to Amazon SNS.
- Determining the message dwell time (the time between the publish timestamp and the hand off to an Amazon SNS endpoint).
Fixes MLPAB-360
- Create a new IAM role with assume role policy for SNS
- Attach a policy for reporting SNS feedback
- https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#sns-2-remediation
- https://docs.aws.amazon.com/sns/latest/dg/sns-topic-attributes.html
> MLPAB-360 - Create a role for SNS feedback

- terraform/environment/backup_plan.tf
- terraform/environment/iam_sns_feedback_role.tf
Logging is an important part of maintaining the reliability, availability, and performance of services. Logging message delivery status helps provide operational insights, such as the following:
- Knowing whether a message was delivered to the Amazon SNS endpoint.
- Identifying the response sent from the Amazon SNS endpoint to Amazon SNS.
- Determining the message dwell time (the time between the publish timestamp and the hand off to an Amazon SNS endpoint).
Fixes MLPAB-285
- pull in SNS feedback role
- (temporarily) enable backup plans for PR environments
- enable feedback for each notification type
- https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#sns-2-remediation
- https://docs.aws.amazon.com/sns/latest/dg/sns-topic-attributes.html
> MLPAB-285 - Logging of delivery status should be enabled for notification messages sent to a topic

- terraform/account/region/default_vpc.tf
To improve the security posture of your VPC, you can configure Amazon EC2 to use an interface VPC endpoint. Interface endpoints are powered by AWS PrivateLink, a technology that enables you to access Amazon EC2 API operations privately. It restricts all network traffic between your VPC and Amazon EC2 to the Amazon network. Because endpoints are supported within the same Region only, you cannot create an endpoint between a VPC and a service in a different Region. This prevents unintended Amazon EC2 API calls to other Regions. 
Fixes MLPAB-373
- Configure an EC2 VPC endpoint for the default VPC
- https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-10-remediation
> MLPAB-373 - Amazon EC2 should be configured to use VPC endpoints that are created for the Amazon EC2 service

- terraform/environment/cloudwatch_application_insights.tf
- terraform/environment/region/cloudwatch_application_insights.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Amazon CloudWatch Application Insights facilitates observability for your applications and underlying AWS resources. It helps you set up the best monitors for your application resources to continuously analyze data for signs of problems with your applications. Application Insights, which is powered by [SageMaker](https://docs.aws.amazon.com/sagemaker/latest/dg/wahtis.html) and other AWS technologies, provides automated dashboards that show potential problems with monitored applications, which help you to quickly isolate ongoing issues with your applications and infrastructure. The enhanced visibility into the health of your applications that Application Insights provides helps reduce mean time to repair (MTTR) to troubleshoot your application issues.
Fixes MLPAB-396
- Create application …
> MLPAB-396 - Create application insights for each app-region

- terraform/account/region/data_sources.tf
- terraform/account/region/variables.tf
- terraform/account/regions.tf
- terraform/account/s3_kms.tf
Use customer managed encryption key for S3 buckets.
Fixes MLPAB-421
- Create an encryption key for S3 and pass it into the region module
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/specifying-kms-encryption.html
> MLPAB-421 - Create a KMS key for S3 buckets

- terraform/account/region/data_sources.tf
- terraform/account/region/s3_lb_access_logs.tf
Use an AWS KMS customer managed key (CMK) when encrypting S3 buckets, and use bucket keys to reduce AWS KMS usage.
Fixes MLPAB-428
- Retrieve key ARN using data source
- Use CMK to encrypt bucket
- Enable Bucket Keys
- Require server side encryption when putting objects
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html#require-sse-kms
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-key.html
> MLPAB-428 - Enable bucket keys encryption with CMK

- terraform/account/rum_cognito_identity_pool.tf
- terraform/account/terraform.tfvars.json
- terraform/account/variables.tf
- terraform/environment/rum_monitoring.tf
- terraform/environment/rum_monitoring_cognito_iam_role.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
The App will use a cognito identity pool to send data to AWS
Fixes MLPAB-442 MLPAB-443
- Create a Cognito identity pool (in global region?)
- Create a Cognito identity
- Create an IAM role for the Cognito identity with `PutRumEvents`
- Create an AWS RUM app monitor
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-RUM-get-started-authorization.html
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-RUM-get-started-create-app-monitor.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rum_app_monitor
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_identity_pool
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_identity_pool_roles_attachm …
> MLPAB-442 / MLPAB-443 - Authorise app to send RUM data

- app/go.mod
- app/go.sum
- app/internal/page/app.go
- app/internal/page/app_test.go
- app/main.go
- app/web/template/layout/page.gohtml
* Add preconnect tag in for AWS RUM calls
* Move javascript to and add async tag to it. This will allow the browser to fetch it sooner in a non blocking
* Add preload tags in the for our CSS and Javascript
* Enable zip compression for static assets with a TTL of 30 days set.
Fixes [MLPAB-478](https://opgtransform.atlassian.net/browse/MPLAB-478)
> Mlpab 478 fe perf

- Makefile
- package.json
- yarn.lock
Fixes https://nvd.nist.gov/vuln/detail/CVE-2022-3517. Dropping cypress-parallel until the package supports mocha v9 - see https://github.com/tnicola/cypress-parallel/pull/134.
I've also set all our JS deps to patch to the next minor version - happy to be challenged on this if there are fears about chain attacks but given our fairly limited dependencies the risk didn't seem too high.
Fixes MLPAB-504
> MLPAB-504: Fix CVE 2022 3517

- .github/workflows/ui_test_job.yml
Optimise Cypress test workflow by using the previously built image instead of rebuilding it
Fixes MLPAB-522
- Use docker compose pull
- Remove docker compose build
> MLPAB-522 - Use docker compose pull instead of docker compose build for Cypress tests

- terraform/environment/container_version_parameter.tf
Use paths in parameter store names so that OIDC roles can safely use IAM policy document wildcards for retrieving container versions
Fixes MLPAB-518
- use modernising-lpa/container-version/${env-name} path format
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_parameter#name
> MLPAB-518 - Use a path in SSM parameter name to enable wildcards

- terraform/environment/terraform.tfvars.json
Finish configuration of UR environment
Fixes MLPAB-528
- Configure auth redirect and public url for UR environment
This has been applied to the UR env with the current production tag deployed
> MLPAB-528 - Configure auth redirect for gov.uk sign in on UR environment

- .github/workflows/docker_job.yml
ECR lifecycle rules were not persisting images we wanted to keep as the image tags didn't contain matching patterns.
ECR lifecycle is
```
keep image tagged latest forever
keep last 10 images with main in tag
keep last 10 images with master in tag
keep untagged images for 1 day
keep all other tags for 14 days
```
Images were not being tagged with latest, main* or master* so were only being persisted for 14 days
Fixes MLPAB-538
- add condition that if github.ref == 'refs/heads/main' add latest and main tags to the image
This should result in the path to live creating an image with `latest`, `main` and `v0.0.0` tags
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_lifecycle_policy
- https://github.com/ministryofjustice/opg-org-infra/blob/main/services/modernis …
> MLAPB-538 - Tag path to live images with latest and main

- cypress.config.js
- cypress/e2e/certificate-provider.cy.js
- cypress/e2e/payment.cy.js
- yarn.lock
This seems to be triggered when the app has just started and has been sporadically triggered on the path to live pipeline in the `certificate-provider` and `payment`. To try to replicate I bought the app down and back up, modified the tests to run multiple times and then ran the cypress suite. I managed to trigger sporadic failures a few times following this approach.
For `certificate-provider` it was a known issue that involves a false a11y failure on an a GDS element. It's still not entirely clear what happens in the app/cypress to sometimes get to this failure but excluding that specific rule seems to have removed the failures locally.
For `payment` there were a couple of issues related to the cookie either existing when it shouldn't or not existing when it should. I've manually unset …
> MLPAB-568: Guard against flaky Cypress test

- app/internal/secrets/secrets.go
- app/internal/secrets/secrets_test.go
- app/main.go
This is potentially still over the top for what we have. I figured there was no point finding an LRU cache to match what we had before because the default size of 1024 was way over what we'd ever need. I've matched the 1 hour TTL but not gone as far as to implement exponential backoff (just doing a simple `errors * delay` instead).
> MLPAB-376 Make cache refresh secrets after a specified duration

- app/internal/app/app.go
- app/internal/page/certificateprovider/login_callback.go
- app/internal/page/certificateprovider/login_callback_test.go
- app/internal/page/certificateprovider/register.go
- app/internal/page/certificateprovider/start.go
- app/internal/page/certificateprovider/start_test.go
- app/internal/page/data.go
- app/internal/page/donor/mock_test.go
- app/internal/page/donor/payment_confirmation.go
- app/internal/page/donor/payment_confirmation_test.go
- app/internal/page/donor/register.go
- app/internal/page/paths.go
- app/web/template/layout/page.gohtml
I took the key design from https://amazon-dynamodb-labs.workshop.aws/game-player-data/core-usage/step1.html, which seemed sensible enough. I was going to expire the code and add a different record to tie the certificate provider to the LPA but realised if you had multiple LPAs we'd then need a dashboard type thing to pick from, so I've gone the simple route of requiring the code each time on sign in. This can obviously be changed later.
> MLPAB-669 Use a single code in link to certificate provider

- .github/workflows/docker_job.yml
- .github/workflows/terraform_environment_job.yml
- .github/workflows/ui_test_job.yml
- .github/workflows/workflow_deploy_to_ur_environment.yml
Maintain a consistent environment for user research sessions by allowing team members to picka tag to build and deploy
Fixes MLPAB-609
- Create a dispatch workflow that deploys to the ur environment
- add checkout tag to relevant jobs that defaults to the current ref
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
- https://github.com/actions/checkout
> MLPAB-609 - Deploy to ur environment from github user interface

- .github/workflows/remove_ingress_job.yml
- .github/workflows/terraform_account_job.yml
- .github/workflows/terraform_environment_job.yml
- .github/workflows/ui_test_job.yml
- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
- .secrets.baseline
Limit the secrets passed to each job so that only those needed are given
Fixes MLPAB-680
- specify secrets for each job on pr workflow
- specify secrets for each job on path to live workflow
- https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
> MLPAB-680 - Specify secrets for each job on all workflows

- app/internal/page/donor/about_payment.go
- app/internal/page/donor/about_payment_test.go
After seeing this in the demo for the Nth time, I figured it should really be doing this
> Use donor's email as default for payment

- cypress/e2e/certificate-provider/enter-reference-number.cy.js
We're still getting flaky failures for the test that lands on one login /.jwks despite seemingly bumping the timeout. Turns out the timeout wasn't boosted for the right event in cypress, it should have been pageLoad. Its a little confusing where to add this on a specific command in the test so I've boosted it for the whole spec instead.
> Actually fix jwks timeout test

- app/internal/page/data.go
- app/internal/page/donor/witnessing_as_certificate_provider.go
- app/internal/page/donor/witnessing_as_certificate_provider_test.go
- app/internal/page/limiter.go
- app/internal/page/limiter_test.go
- lang/en.json
I felt that embedding the rate limiter state in the Lpa was going to be nicer than having a global map of limiters (that would then require cleaning up, and wouldn't scale if we had more than 1 container).
Also missed that I'd changed some content in my previous PR copy and pasting from the GDS pattern, but not reverted it.
> MLPAB-550 Rate limit entry of the witness code

- terraform/environment/.terraform.lock.hcl
- terraform/environment/healthcheck.tf
- terraform/environment/region/modules/app/alb.tf
- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/terraform.tf
- terraform/environment/variables.tf
Monitor service uptime
Uptime percentage is reported to the us-east-1 region (because that's where the health-checks exist, even though the test from other regions)
Fixes MLPAB-696
- Create a route53 endpoint check
- Allow ingress for route53 health checks
- https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/health-checks-types.html
> MLPAB-696 - Create healthcheck

- .github/workflows/workflow_path_to_live.yml
Fix path to live
Get quick feedback on jobs without having to delve into the actions log
Fixes MLPAB-750
- pipe a summary of the plan to an output
- use actions scripts to push a message to PR (or any other issue type) comments
- https://github.com/actions/github-script#comment-on-an-issue
- https://github.com/hashicorp/setup-terraform/blob/main/README.md
To capture the plan summary:
The `-no-color` option is used to disable colourised output from the terraform plan command, and the `-ioE` options for grep are used to perform a case-insensitive search (-i), to output only the matching text (-o), and to use extended regular expressions (-E) for matching the numbers in the summary line.
> MLPAB-750 - fix path to live

- app/internal/app/app.go
- app/internal/app/app_test.go
- app/internal/identity/yoti_client.go
- app/internal/identity/yoti_client_test.go
- app/internal/page/certificateprovider/identity_with_yoti.go
- app/internal/page/certificateprovider/identity_with_yoti_test.go
- app/internal/page/certificateprovider/mock_YotiClient_test.go
- app/internal/page/certificateprovider/register.go
- app/internal/page/certificateprovider/register_test.go
- app/internal/page/donor/identity_with_yoti.go
- app/internal/page/donor/identity_with_yoti_test.go
- app/internal/page/donor/mock_YotiClient_test.go
- app/internal/page/donor/register.go
- app/internal/page/donor/register_test.go
- app/internal/page/paths.go
- app/internal/page/yoti_redirect.go
- app/internal/page/yoti_redirect_test.go
- app/internal/sesh/sesh.go
- app/main.go
- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
I think that having a single scenario like this will make life easier, since we want the same data from both actors. I'm using the same pattern as we do for One Login, storing data in a session and adding a facade redirect handler.
> MLPAB-785 Fix yoti redirect

- .github/workflows/terraform_environment_job.yml
- .github/workflows/toggle_public_access_job.yml
- .github/workflows/workflow_manage_public_access_ur_environment.yml
- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Make it easy for team members to toggle UR availability using github actions
Fixes MLPAB-799
- split public access variable into separate var
- create a job to toggle public access from github actions
- manage public access for production env specifically
- Configuring this to target a single environment that isn't ur for now while I test
* [] I have performed a self-review of my own code
> MLPAB-799 - Toggle public access for UR environment

- renovate.json
Automate minor and patch updates and wait a few days for updates to be seen as stable
Fixes MLPAB-819
- create package rules for minor and patch updates
> MLPAB-819 - auto merge minor and patch updates, and wait 3 stability days

- .github/workflows/detect_changes_to_app_job.yml
- .github/workflows/tags_job.yml
- .github/workflows/workflow_path_to_live.yml
- .github/workflows/workflow_pr.yml
On https://github.com/ministryofjustice/opg-modernising-lpa/pull/429 I spotted that it wasn't actually doing the build/test/etc. on the first commit. I think this fixes that by checking against `origin/main` if the PR is opened, otherwise doing the last push. But I'm not entirely sure why they were separated out, so maybe this breaks something else?
> Detect changes when PR is first opened against main

- terraform/account/.terraform.lock.hcl
- terraform/account/cloudwatch_kms.tf
- terraform/account/region/s3_lb_access_logs.tf
Deploy the second region resources
Fixes MLPAB-912
- Do not create an S3 ACL as they are no longer enabled/allowed for bucket by default (the default permissions are the same as the "private" ACL. This is suitable for the use case.
- ensure that replicated KMS keys also have the correct policies attached
https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html
> MLPAB-912 - Fixes to second region deployment

- .secrets.baseline
- README.md
- app/go.mod
- app/go.sum
- app/internal/app/app.go
- app/internal/app/lpa_store.go
- app/internal/app/lpa_store_test.go
- app/internal/page/donor/choose_attorneys.go
- app/internal/page/donor/choose_attorneys_test.go
- app/internal/page/donor/choose_people_to_notify.go
- app/internal/page/donor/choose_people_to_notify_test.go
- app/internal/page/donor/choose_replacement_attorneys.go
- app/internal/page/donor/choose_replacement_attorneys_test.go
- app/internal/page/donor/mock_test.go
- app/internal/page/donor/register.go
- app/internal/random/random.go
We were getting flaky test failures during cypress runs. After some digging the common pattern was an error thrown when getting an entity from dynamodb where we expected a single result but got multiple. Local testing showed we were getting ID collisions on LPAs during multiple cypress test runs which explained why fresh environments (and a clear local dynamodb table) rarely had errors.
This change moves to using UUIDs for LPAs and the associated Attorneys, Replacement Attorneys and People To Notify in to protect against any collisions going forward.
There may be some other flaky tests that were outside of this problem but from running a few concurrent cypress runs locally I've not seen a repeat of the error occur.
Fixes MLPAB-898
> MLPAB-898: Use UUID strings for LPA, Attorney, RA and PTN

- terraform/environment/regions.tf
Allow users from new IP ranges to access non-production environments
Fixes MLPAB-1037
- Upgrade the allow list module to pull in the new ranges
> MLPAB-1037 - upgrade allow list module to get new IPs

- terraform/environment/dynamodb.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
Use the V2 method for creating a global table replica in a second region
Fixes MLPAB-1035
- Add table replica block
- remove inline block
- ignore table replicas in the dynamodb table resource
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table_replica
> MLPAB-1035 - Use table replica resource instead of inline block

- .github/workflows/workflow_destroy_pr_environment.yml
- .github/workflows/workflow_path_to_live.yml
Path to live fails due to missing input
Destroy environment job needs pagerduty token
Fixes MLPAB-1051
- go_unit_tests needs create_tags
- pass in-line `-var` for pagerduty secret
> MLPAB-1051 - unit tests need tag job outputs for pact publishing

- .github/workflows/workflow_destroy_pr_environment.yml
- .github/workflows/workflow_terraform_environment_cleanup.yml
Scheduled destroy job is failing due to missing input variable
Fixes MLPAB-1057
- Add input variable to environment
> MLPAB-1057 - set env vars for both destory jobs where they need a pagerduty api key

- terraform/environment/iam_ecs_execution_role.tf
- terraform/environment/refactor.tf
- terraform/environment/region/ecs.tf
- terraform/environment/region/iam_execution_policy.tf
- terraform/environment/region/rum_monitoring.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
Clean up regional resources in root of environment configuration
Fixes MLPAB-963
- Move regional secrets for RUM to region module
- Create regional policy documents and attach them to the ECS execution role
> MLPAB-963 - refactor regional policies for execution role to region module

- terraform/environment/region/cloudwatch_application_insights.tf
Application Insights fail to be provisioned by the terraform aws provider, causing the deploy job to fail
Fixes MLPAB-1072
- turn of auto configure as unsupported states cause a problem
there's a bug reported on the aws provider https://github.com/hashicorp/terraform-provider-aws/issues/27277
> MLPAB-1072 - Fix issues with app insights

- .codecov.yml
- .secrets.baseline
- app/internal/app/app.go
- app/internal/app/app_test.go
- app/internal/page/app_data.go
- app/main.go
- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
- web/template/layout/login-header.gohtml
Pulls the URL for the onelogin account path via env var rather than hard coding. Defaulting to the integration URL for now but we can vary this once we are in private beta.
Fixes MLPAB-1048
> MLPAB-1048: Use env var to set onelogin URL

- terraform/environment/region/ecs.tf
- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/region/modules/app/variables.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
We currently allow any environment to call all instances of an API. This is too permissive
Fixes MLPAB-1143
- pass list of ARNs to ECS task policy using variables via TFVARs
- limit the ARNs per environment
> MLPAB-1143 - Limit what endpoints an environment can call

- .gitignore
- terraform/environment/.terraform.lock.hcl
- terraform/environment/global/iam_s3_antivirus.tf
- terraform/environment/global/outputs.tf
- terraform/environment/region/ecs.tf
- terraform/environment/region/iam_execution_policy.tf
- terraform/environment/region/modules/s3_antivirus/alarms.tf
- terraform/environment/region/modules/s3_antivirus/data_sources.tf
- terraform/environment/region/modules/s3_antivirus/iam.tf
- terraform/environment/region/modules/s3_antivirus/main.tf
- terraform/environment/region/modules/s3_antivirus/s3.tf
- terraform/environment/region/modules/s3_antivirus/terraform.tf
- terraform/environment/region/modules/s3_antivirus/variables.tf
- terraform/environment/region/modules/uploads_s3_bucket/outputs.tf
- terraform/environment/region/s3_antivirus.tf
- terraform/environment/region/terraform.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
Scan and tag objects uploaded as reduced fees evidence
Fixes MLPAB-1155
- trigger antivirus scans when objects are uploaded (execute lambda on object put event)
- tag objects as `ok` or `infected`
- test with an EICAR test file
put an object with an EICAR signature (EICARs aren't committed to the repo)
```sh
aws-vault exec mlpa-dev -- aws s3api put-object --bucket uploads-opg-modernising-lpa-<environment>-<eu-west-1> --key test_signature/EICAR.pdf --body region/modules/s3_antivirus/EICAR.pdf --server-side-encryption AES256
```
- https://en.wikipedia.org/wiki/EICAR_test_file
- the terraform aws provider `aws_cloudwatch_log_group` asks for a `kms_key_id`, but it wants a KMS key arn https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group#kms_key_id
> MLPAB-1155 - Deploy antivirus scanning infrastructure

- .github/workflows/workflow_pr.yml
- terraform/environment/region/modules/app/ecs.tf
The ECS task role had permission to use all DynamoDB actions which is not necessary
Fixes MLPAB-1150
- replace `dynamodb:*` with specific actions required for the app to function
I ran the full ui suite on the env and got a pass
https://github.com/ministryofjustice/opg-modernising-lpa/actions/runs/5615133082/job/15214857346
- https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazondynamodb.html
> MLPAB-1150 - limit dynamodb actions for ECS task role

- app/internal/page/donor/check_your_lpa.go
- app/internal/page/donor/check_your_lpa_test.go
- app/internal/page/donor/lpa_details_saved.go
- app/internal/page/donor/lpa_details_saved_test.go
- app/internal/page/donor/register.go
- cypress/e2e/donor/check-your-lpa.cy.js
- web/template/check_your_lpa.gohtml
- web/template/lpa_details_saved.gohtml
Now we contact the CP on the donor checking their LPA we can no longer rely on the paid task being completed to vary the content for these two pages. I've relied on a query param here as it seemed the most straightforward way of dealing with the first time the donor hits `/lpa-details-saved` when the check and send task will always be complete.
Fixes MLPAB-1149
> MLPAB-1149: Update /check-your-lpa and /lpa-details-saved variable template logic 

- terraform/environment/region/ecs.tf
Pull additional CIDR ranges to allow those outside of MoJ sites to access an environment
Fixes MLPAB-1303
- Pull from parameter store
- consolidate list into var for security group
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ssm_parameter
- https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html#what-is-a-parameter
- https://developer.hashicorp.com/terraform/language/functions/split
> MLPAB-1303 pull additional allowed ingress CIDR ranges

- terraform/environment/.terraform.lock.hcl
- terraform/environment/region/modules/uploads_s3_bucket/lambda.tf
- terraform/environment/region/modules/uploads_s3_bucket/variables.tf
- terraform/environment/region/uploads_s3_bucket.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Create batch replication jobs every 15 minutes when schedulers are enabled on an environment
Fixes MLPAB-1296
- create an Eventbridge scheduler
- Create a role for the scheduler to invoke the create batch job lambda function
- only create and start the scheduler if enabled for the environment
- https://docs.aws.amazon.com/scheduler/latest/UserGuide/schedule-types.html
- https://docs.aws.amazon.com/scheduler/latest/UserGuide/managing-targets-templated.html#managing-targets-templated-lambda
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/scheduler_schedule
> MLPAB-1296 - add a scheduler to invoke the lambda function

- terraform/account/.terraform.lock.hcl
- terraform/account/reduced_fees_uploads_s3_kms.tf
Use customer managed encryption for objects uploaded to the reduced fees uploads bucket
Fixes MLPAB-1312
- reuse the pattern for other kms keys
- add the default policy for adding
- https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html#key-policy-default-allow-root-enable-iam
> MLPAB-1312 - create a key for reduced fees uploads buckets

- .github/workflows/workflow_pr.yml
- terraform/account/cloudwatch_kms.tf
- terraform/account/dynamodb_kms.tf
- terraform/account/secrets_manager_kms.tf
Ensure the AWS account can manage the key and it's IAM policies
Fixes MLPAB-1313
- add default policy to keys
- ensure policy is appended to replica keys too
- https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-default.html#key-policy-default-allow-root-enable-iam
> MLPAB-1313 - add default policy 

- .github/workflows/workflow_destroy_pr_environment.yml
- .github/workflows/workflow_terraform_environment_cleanup.yml
Environment cleanup workflows fail to set the correct terraform version
Fixes MLPAB-1360
- Implement version parsing from the versions.tf file used in environment deploy workflows
- https://github.com/ministryofjustice/opg-modernising-lpa/pull/644
> MLPAB-1360 - set terraform version from versions.tf

- .github/workflows/on_path_to_live_failure.yml
Path to live notifications when pipeline fails stopped working when the name of the path to live workflow changed.
Fixes MLPAB-1352
- use correct name for path to live workflow
> MLPAB-1352 - Fix notifications for path to live failures

- terraform/account/region/dns_firewall.tf
- terraform/account/region/modules/dns_firewall/data_sources.tf
- terraform/account/region/modules/dns_firewall/main.tf
- terraform/account/region/modules/dns_firewall/terraform.tf
- terraform/account/region/modules/dns_firewall/variables.tf
Reduce egress from app to permitted targets only
Fixes MLPAB-1367
- create an account level DNS firewall
- configure some permitted entries 
- block all else
- set to monitor mode (does not block requests)
A further PR will associate environment resources with the firewall
- https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-dns-firewall.html
> MLPAB-1367 - Create a dns firewall in the account

- .github/workflows/analysis-codeql.yml
The detected version of Go is lower than the version specified in go.mod (in the code scanning job)
Fixes MLPAB-1377
- Setup go and specify version
- https://github.com/actions/setup-go#basic
> MLPAB-1377 - Setup go while specifying version

- web/assets/data-loss-warning.js
- web/assets/main.js
Ensures that the cookie containing form values can be compared against current form values on button clicks.
Upon investigating this bug I also took some time to get to the bottom of certain GDS components that rely on JS intermittently malfunctioning. This could be seen in places like the dashboard where the tabbed card view would sometimes show as a stacked list of cards. It looks like it was a timing issue as once I wrapped the init code in a couple of checks for the content being ready I didn't experience any issues.
Fixes MLPAB-1147.
> MLPAB-1147: Fix destructive changes dialog flakiness

- terraform/environment/region/event_bus.tf
- terraform/environment/region/modules/event_bus/main.tf
- terraform/environment/region/modules/event_bus/variables.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Add permissions to event bus to allow specified account to send events to the bus.
For VEGA-2090 #minor
Re-used permissions set from Sirius. I added an environment-level config parameter called `receive_account_id`, if it's an empty string then the permission isn't created.
VS Code was much more helpful with this than I expected.
> Allow Sirius accounts to send events

- .github/workflows/workflow_pr.yml
- terraform/account/region/vpc_endpoints.tf
Direct requests to AWS services via a VPC endpoint to reduce the egress vector through the internet gateway
Fixes MLPAB-1370
- Create interface endpoints for services we use
- https://docs.aws.amazon.com/vpc/latest/privatelink/privatelink-access-aws-services.html
> MLPAB-1370 - create endpoints for logs, ssm, secrets manager and ecr

- terraform/account/region/vpc_endpoints.tf
Direct requests to AWS services via a VPC endpoint to reduce the egress vector through the internet gateway
Fixes MLPAB-1481
- create events endpoint 
- name S3 and DynamoDB gateway endpoints
> MLPAB-1481 - Create endpoint for eventbridge

- cypress/e2e/attorney/progress.cy.js
- internal/actor/attorney_provided.go
- internal/actor/attorney_provided_test.go
- internal/app/dashboard_store.go
- internal/app/dashboard_store_test.go
- internal/page/attorney/mock_AttorneyStore_test.go
- internal/page/attorney/progress.go
- internal/page/attorney/progress_test.go
- internal/page/attorney/register.go
- internal/page/attorney/sign.go
- internal/page/attorney/sign_test.go
- internal/page/dashboard.go
- internal/page/data.go
- internal/page/data_test.go
- internal/page/fixtures/attorney.go
- internal/page/fixtures/donor.go
- internal/page/paths.go
- lang/cy.json
- lang/en.json
- web/template/attorney_fixtures.gohtml
- web/template/attorney_progress.gohtml
- web/template/dashboard.gohtml
I needed a way to check on the dashboard that the attorney signed after the certificate provider (after the donor), since getting the certificate provider signed at is difficult/impossible with the way the data is set up I came up with the solution of storing `LpaSignedAt` on the attorney data and checking that matches the current one. It's a bit weird, but hopefully makes sense.
> MLPAB-922 Add attorney progress page

- .github/workflows/workflow_pr.yml
- terraform/account/region/vpc_endpoints.tf
Fixes MLPAB-1470
- set the current account as principal on gateway endpoints
- create a basic allow policy for each endpoint limiting access to the account
- https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-access.html
> MLPAB-1470 - Create endpoint policies

- terraform/environment/.terraform.lock.hcl
- terraform/environment/region/modules/event_received/lambda.tf
- terraform/environment/region/modules/event_received/outputs.tf
- terraform/environment/region/modules/s3_antivirus/s3.tf
- terraform/environment/region/modules/s3_antivirus/variables.tf
- terraform/environment/region/s3_antivirus.tf
Events were not making it to the lambda function through eventbridge
Fixes MLPAB-1506
- Pass events received lambda function into S3 antivirus config
- Add notification for object logging to events received lambda
I will later on evaluate refactoring the notification into the bucket module itself
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification#trigger-multiple-lambda-functions
> MLPAB-1506 - Fix events recevied triggering from object tagging events

- .github/workflows/workflow_pr.yml
- lang/cy.json
If the End of Workflow job gets a status of skipped, it will count as successful and allow a PR to be merged
Fixes MLPAB-1513
- Use success of the preceding important job
- Exit 0 if successful
- Exit 1 if not
> MLPAB-1513 - Do not allow End of Workflow to be skipped

- terraform/account/region/waf.tf
Allow total maximum upload size at WAF (5 documents x 20MB each)
Fixes MLPAB-1420
- set size constraint to 100 megabytes (in bytes)
- https://docs.aws.amazon.com/waf/latest/developerguide/waf-oversize-request-components.html
- https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-size-constraint-match.html
> MLPAB-1420 - Change max upload size to match Sirius WAF

- docs/pull_request_template.md
- terraform/environment/region/modules/s3_antivirus/main.tf
- terraform/environment/region/modules/s3_antivirus/variables.tf
- terraform/environment/region/s3_antivirus.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Reduce the impact of cold starts on users
Fixes MLPAB-1515
- Create provisioned concurrency
- add validation to variable so that maximum concurrency isn't accidentally set too high
- Also, remove checklist from PR template
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_provisioned_concurrency_config
- https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html?icmpid=docs_lambda_console
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_alias
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#publish
> MLPAB-1515 - Add provisioned concurrency for S3 AV Lambda

- terraform/environment/region/modules/uploads_s3_bucket/s3_object_replication.tf
Notify the team when objects fail to replicate
Fixes MLPAB-1527
- Create a metric alarm for failed replications
- Send alert via pagerduty to the team
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/viewing-replication-metrics.html
> MLPAB-1527 - Create metric alarm for failed replications

- terraform/account/region/modules/s3_batch_manifests/data_sources.tf
- terraform/account/region/modules/s3_batch_manifests/s3.tf
- terraform/account/region/modules/s3_batch_manifests/variables.tf
- terraform/account/region/s3_batch_manifests.tf
- terraform/account/region/variables.tf
- terraform/account/regions.tf
- terraform/environment/region/modules/lambda/variables.tf
Fixes MLPAB-1366 MLPAB-1580
- MLPAB-1580 format variables file
- Use uploads bucket encryption key to encrypt manifests bucket
> MLPAB-1366 - Use CMK for manifests storage

- terraform/environment/region/modules/event_bus/data_sources.tf
- terraform/environment/region/modules/event_bus/main.tf
Capture failed events so they can be retried
Fixes MLPAB-1501
- create a SQS dead letter queue for the environment event bus
- create alarm for more than 1 item (approx) in the queue
- https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-rule-dlq.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target#dead_letter_config
> MLAB-1501 - Use a dead letter queue for failed put-events to Sirius

- terraform/environment/region/modules/uploads_s3_bucket/s3_bucket_lifecycles.tf
Keep storage down and only hold documents as long as we need them
Fixes MLPAB-1579
- add rule to expire objects with `replicate=true` after 30 days
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html
> MLPAB-1579 - Expire objects that have been replicated

- .github/workflows/workflow_destroy_pr_environment.yml
The Weblate environment shouldn't be destroyed. When Weblate PRs close the destroy environment workflow runs and fails because the calculated name for environment it tries to destroy doesn't exist, and the Weblate environment is protected.
Fixes MLPAB-1628
- Don't run the workflow when the weblate pr closes
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-branches
> MLPAB-1628 - Don't run destroy job when weblate PRs close

- terraform/environment/region/modules/lambda/alarms.tf
If lambda functions the service depends on fail, the team need to know. 
Fixes MLPAB-1657
- Create a metric alarm for lambda function errors
- set the threshold low due to low use of features in environments
- Use custom cloudwatch alarms sns topic to forward alert via pagerduty to team
> MLPAB-1657 - Notify team when a lambda function has unepected errors

- terraform/account/sqs_kms.tf
- terraform/environment/region/modules/event_bus/main.tf
Use customer managed encryption for better control over usage
Fixes MLPAB-1585
- Use CMK for SQS
- https://aquasecurity.github.io/tfsec/v1.28.4/checks/aws/sqs/queue-encryption-use-cmk/
> MLPAB-1585 - Use CMK for SQS

- .github/workflows/terraform_account_job.yml
- .github/workflows/terraform_environment_job.yml
Naming on production deploy job was wrong
Fixes MLPAB-1696
- Name Production and Demo deploy job correctly
- Use environment name in terraform_environment_workflow
> MLPAB-1696 - add naming to terraform environment workflow

- terraform/environment/region/modules/app/alb.tf
This pull request fixes an issue with the security group configuration. The application load balancer is configured to redirect `http`/`:80` to `https`/`:443`, but the application security group doesn't allow connections via `http`/`:80`.
This work is unticketed.
This pull request adds a security group rule to allow connections on `:80` to allow the ALB to handle redirections to `:443`, if public access is enabled (e.g. for the demo app).
> Add security group ingress rule for port :80, to allow ALB to handle redirections for publicly accessible services

- terraform/environment/terraform.tfvars.json
So that we can demonstrate end-to-end journeys in the demo/integration environments
> Use demo LPA Store environment

- terraform/environment/.terraform.lock.hcl
- terraform/environment/global.tf
- terraform/environment/global/cloudwatch_application_insights.tf
- terraform/environment/global/variables.tf
- terraform/environment/global/versions.tf
- terraform/environment/region/cloudwatch_application_insights.tf
- terraform/environment/region/modules/app/versions.tf
- terraform/environment/region/modules/application_logs/versions.tf
- terraform/environment/region/modules/ecs_autoscaling/versions.tf
- terraform/environment/region/modules/event_bus/versions.tf
- terraform/environment/region/modules/event_received/versions.tf
- terraform/environment/region/modules/lambda/version.tf
- terraform/environment/region/modules/mock_onelogin/versions.tf
- terraform/environment/region/modules/s3_antivirus/versions.tf
- terraform/environment/region/modules/uploads_s3_bucket/versions.tf
- terraform/environment/region/variables.tf
- terraform/environment/region/versions.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
- terraform/environment/versions.tf
Monitor the services used by the app and raise alerts to the team for abnormalities
Fixes MLPAB-1962
- enable app insights and check auto-configure is working
- enable for specific environments
- ~route alarms to Pagerduty~ I'm going to start a new PR for alerts to pagerduty
~Note: turn off for default (terraform/environment/terraform.tfvars.json) before merging~ done
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/applicationinsights_application
> MLPAB-1062 - Enable app insights

- renovate.json
Automate dependency upgrade PRs for major versions
Fixes MLPAB-1807
- set prCreation to immediate
- https://docs.renovatebot.com/configuration-options/
> MLPAB-1807 - raise major prs immediately after stability days

- terraform/environment/region/cloudwatch_application_insights.tf
- terraform/environment/region/pagerduty.tf
- terraform/environment/terraform.tfvars.json
Notify team when there are opsitems generated for cloudwatch application insights
Fixes MLPAB-1062
- add opsitems and sns topic
- sub pagerduty to sns topic
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/applicationinsights_application
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic
> MLPAB-1062 - add opsitems notifications to cloudwatch application insights

- terraform/account/README.md
- terraform/account/s3_replication_role.tf
- terraform/environment/region/modules/app/README.md
This role was moved to environment level because we exceeded the limit of policies attached to an IAM role (10). That move has disrupted to configuration of Sirius, and made it quite difficult to tighten up.
I've increased the limit to 20, which should be more than enough.
Fixes MLPAB-1839
- Create account level replication role
- https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html
> MLPAB-1839 - reinstate account level replicatoin role

- .github/workflows/workflow_destroy_pr_environment.yml
The Weblate environment is persistent and protected from destruction. The job wasn't correctly skipping destroy steps for the environment and generating a workspace name that never existed, causing the job to fail.
Fixes MLPAB-1906
- Don't run destroy step if the closing branch is `weblate-pr`
- remove unused step for protecting workspaces
- remove branch ignore condition (as we don't merge to `weblate-pr`)
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
> MLPAB-1906 - Fix destroy environment job for Weblate PRs

- .github/workflows/workflow_destroy_pr_environment.yml
Prevent the PR environment destroy job failing when a workspace doesn't exist
- Create a workspace if it doesn't exist
This lets the rest of the job pass very quickly
> MLPAB-1906- create missing workspaces so that the destroy job never fails

- terraform/account/README.md
- terraform/account/region/README.md
- terraform/account/region/modules/antivirus_definitions/README.md
- terraform/account/region/modules/dns_firewall/README.md
- terraform/account/region/modules/s3_batch_manifests/README.md
- terraform/account/region/modules/s3_bucket_event_notifications/README.md
- terraform/environment/README.md
- terraform/environment/global/README.md
- terraform/environment/region/README.md
- terraform/environment/region/modules/app/README.md
- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/region/modules/application_logs/README.md
- terraform/environment/region/modules/ecs_autoscaling/README.md
- terraform/environment/region/modules/ecs_autoscaling/main.tf
- terraform/environment/region/modules/event_bus/README.md
- terraform/environment/region/modules/event_received/README.md
- terraform/environment/region/modules/fault_injection_simulator_experiments/README.md
- terraform/environment/region/modules/fault_injection_simulator_experiments/main.tf
- terraform/environment/region/modules/lambda/README.md
- terraform/environment/region/modules/mock_onelogin/README.md
- terraform/environment/region/modules/s3_antivirus/README.md
- terraform/environment/region/modules/uploads_s3_bucket/README.md
- terraform/environment/terraform.tfvars.json
Use a better metric for auto-scaling to make it more responsive
Fixes MLPAB-1940 MLPAB-1941
- bump documentation
- use Maximum instead of Average for CPU tracking
- Split FIS experiment into one for each action
- Ignore desired count so after creation, only auto-scaling controls the number of tasks. (this prevents deployments interfering with desired count)
> MLPAB-1940 MLPAB-1941 - set autoscaling metric for CPU to be Max rather than Avg

- .github/workflows/workflow_destroy_pr_environment.yml
Use a new OIDC role that has permission to delete the container insights log group
Fixes MLPAB-1993
- Assume OIDC role modernising-lpa-github-actions-cloudwatch-log-group-delete before deleting log group
> MLPAB-1993 - Fix PR environment destroy permissions to delete container insights log groups

- terraform/account/opensearch_kms.tf
Fix malformed key policy breaking path to live
Fixes MLPAB-2012
- add account root as principal while conditions restrict to opensearch serverless
- https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html
> MLPAB-2012 - add principals to the opensearch cmk policy

- terraform/environment/README.md
- terraform/environment/opensearch.tf
Manage encryption
Fixes MLPAB-1966
- pull in account level key
- Use CMK in Opensearch Serverless security policy
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearchserverless_security_policy
- https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-encryption.html
> MLPAB-1966 - use customer managed key for opensearch serverless

- terraform/environment/README.md
- terraform/environment/opensearch.tf
- terraform/environment/region/pagerduty.tf
Notify the team of problems with opensearch
Fixes MLPAB-1979
- Create metric alarms for 4xx and 5xx opensearch metrics
- Notify team of alarms via pagerduty
- fix integration keys for other alerts
- https://docs.aws.amazon.com/opensearch-service/latest/developerguide/monitoring-cloudwatch.html
> MLPAB-1979 - add alarms for 4xx and 5xx opensearch metrics

- internal/app/donor_store.go
- internal/app/donor_store_test.go
This isn't currently possible via the supporter UI but this adds some protection for our future selves making changes to store code or the design that could inadvertently allow this.
Fixes MLPAB-2020
> MLPAB-2020: Protect against linking LPA to more than one donor

- .pre-commit-config.yaml
- terraform/account/README.md
- terraform/account/dynamodb_exports_s3_kms.tf
- terraform/account/reduced_fees_uploads_s3_kms.tf
- terraform/account/region/README.md
- terraform/account/region/dynamodb_exports_s3_bucket.tf
- terraform/account/region/modules/dynamodb_exports_s3_bucket/README.md
- terraform/account/region/modules/dynamodb_exports_s3_bucket/data_sources.tf
- terraform/account/region/modules/dynamodb_exports_s3_bucket/main.tf
- terraform/account/region/modules/dynamodb_exports_s3_bucket/variables.tf
- terraform/account/region/modules/dynamodb_exports_s3_bucket/versions.tf
- terraform/account/region/variables.tf
- terraform/account/regions.tf
Create an encrypted S3 bucket for DynamoDB exports used for Opensearch Ingestion Pipelines
Fixes MLPAB-2027
- create a KMS key for bucket encryption
- create a bucket for DynamoDB exports
- turn off terraform-docs pre-commit hook (will be replaced with an automation later)
> MLPAB-2027 create account level bucket for dynamodb exports

- terraform/account/region/dynamodb_exports_s3_bucket.tf
- terraform/account/region/modules/dynamodb_exports_s3_bucket/main.tf
- terraform/account/region/modules/dynamodb_exports_s3_bucket/variables.tf
- terraform/account/region/variables.tf
- terraform/account/regions.tf
Create encrypted S3 bucket for DynamoDB exports used by OpenSearch Ingestion Pipelines
Fixes MLPAB-2027
- don't use CMK for DynamoDB exports (for now)
> MLPAB-2027 - Don't use CMK for bucket SSE

- terraform/account/region/modules/dynamodb_exports_s3_bucket/main.tf
Create encrypted S3 bucket for DynamoDB exports used by OpenSearch Ingestion Pipelines
Fixes MLPAB-##
- Remove encryption altogether for now and reintroduce later when pipeline works
> MLPAB-2027 - remove bucket encryption for exports (temporarily)

- cmd/event-logger/main.go
- cmd/event-received/main.go
- cmd/mlpa/main.go
This has been annoying me for a while, and I keep forgetting to update
> Use BaseEndpoint instead of deprecated resolver for aws config 

- terraform/environment/opensearch_ingestion_pipeline.tf
- terraform/environment/region/modules/app/ecs.tf
Save build time by not deploying ingestion pipelines when they aren't needed. This will not need to be per environment, but instead will be enabled when dependant work is completed.
Fixes MLPAB-2067
- create a flag
- create resources if true
- re-enable app search indexing
> MLPAB-2067 - Only deploy OpenSearch Ingestion Pipeline when needed

- terraform/environment/region/modules/s3_antivirus/data_sources.tf
- terraform/environment/region/modules/s3_antivirus/main.tf
- terraform/environment/region/modules/s3_antivirus/variables.tf
- terraform/environment/region/s3_antivirus.tf
Remove VPC config as lambda function doesn't need to access VPC resources
Fixes MLPAB-2074
- remove vpc config from lambda function
- https://docs.aws.amazon.com/lambda/latest/dg/foundation-networking.html#foundation-nw-connecting
> MLPAB-2074 S3 antivirus doesnt need VPC access

- terraform/environment/region/modules/event_received/lambda.tf
- terraform/environment/region/modules/mock_onelogin/ecs.tf
- terraform/environment/terraform.tfvars.json
AWS cost optimisation has recommended assigning smaller resources for the mock login ECS task.
Fixes MLPAB-2040
- assign half the memory and cpu to the ECS task based on cost optimisation recommendation
> MLPAB-2040 - Rightsize mock ECS resources to save costs

- internal/lpastore/client_test.go
- internal/lpastore/lpa.go
- internal/lpastore/lpa_test.go
To be used in CP opt-out.
Fixes MLPAB-1535
The property is already in the LPA Store, so this just adds it to structs, testing and Pact contract.
> Add `channel` to LPAs returned from LPA Store

- cypress/smoke/smoke.cy.js
The previous run managed to fail on the redirect to onelogin, so increasing both to see if I can at least get a passing run
> MLPAB-1849 Increase waits for smoke test

- terraform/account/opensearch.tf
Avoid collisions with existing collections
Fixes MLPAB-2092
- rename account level include "shared"
> MLPAB-2029 - rename account level opensearch collection shared

- .github/workflows/workflow_destroy_pr_environment.yml
- .github/workflows/workflow_terraform_environment_cleanup.yml
The destroy and cleanup jobs fail because the terraform evaluates the lambda zip file to generate a base64 encoded sha256sum. 
Fixes MLPAB-2167
- pull version tag and download lambda zips to the correct path during environment cleanup job
- pull version tag and download lambda zips to the correct path during environment destroy job
> MLPAB-2167 destroy job needs zip files to complete

- terraform/account/region/modules/dynamodb_exports_s3_bucket/main.tf
Automatically clear down exports
Fixes MLPAB-2181
- add lifecycle to expire objects after 30 days
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration
> MLPAB-2181 - add lifecycle policy to dynamodb exports bucket

- terraform/account/opensearch.tf
Allow access to programmatically delete PR environment indexes
Fixes MLPAB-2193
- Allow from public on the development collection
- https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-network.html
> MLPAB-2193 - grant public access to the development collection

- internal/app/donor_store.go
- internal/app/donor_store_test.go
- internal/page/supporter/donor_access.go
- internal/page/supporter/donor_access_test.go
- internal/page/supporter/mock_DonorStore_test.go
- internal/page/supporter/register.go
To protect against errors between writes.
Fixes MLPAB-2171
> MLPAB-2171: Make deleting donor access transactional

- cmd/event-received/sirius_event_handler.go
- cmd/event-received/sirius_event_handler_test.go
Fixes MLPAB-2150.
I noticed all the tests were silently erroring when trying to marshal a partial struct that contained an unset enum using `json` vs `attributevalue` so I updated all usages in the tests.
> MLPAB-2150: Add early exits when statuses already set

- cmd/event-received/handlers.go
- cmd/event-received/lpastore_event_handler_test.go
- cmd/event-received/sirius_event_handler_test.go
- internal/actor/donor_provided.go
- internal/actor/donor_provided_test.go
- internal/app/donor_store.go
- internal/app/donor_store_test.go
- internal/app/organisation_store.go
- internal/app/organisation_store_test.go
- internal/page/donor/check_your_lpa.go
- internal/page/donor/check_your_lpa_test.go
I think this is the best way to tackle the problem as it allows us to modify how we interpret the hashes, and in a way that each one can drift without affecting the other.
> MLPAB-2069 Add versioning to hashes and exclude some fields from CheckedHash

- docs/runbooks/rebuilding_the_opensearch_index.md
- terraform/environment/opensearch_pipeline/lpas_stream_pipeline_configuration.yaml.tftpl
At the moment, the export raises an unauthorised error (the pipeline works despite the error)
Fixes MLPAB-2240
- Comment out db export block as not needed for any environments
- Add instructions to uncomment the export block
> MLPAB-2240 - turn off db exports on pipelines for now

- .github/workflows/docker_job.yml
- internal/build-trigger
Address warnings on pipeline
Fixes MLPAB-2205
- update buildx version to 0.15.1
- https://github.com/docker/setup-buildx-action?tab=readme-ov-file
- https://github.com/docker/buildx
> MLPAB-2205 - address buildx version requirement on pipelines

- terraform/account/terraform.tfvars.json
- terraform/environment/terraform.tfvars.json
Isolate alerts for productions resources to their own pagerduty service
Fixes MLPAB-2166
- Use the production pagerduty service for producton account and environment
> MLPAB-2166 - use new pagerduty service for production alerts

- terraform/environment/region/modules/event_received/lambda.tf
Fix access denied on kms:decrypt with aws/lambda key
Fixes MLPAB-2177 
- let event received role decrypt using the aws/lambda key
> MLPAB-2177 - fix permission denied on decrypt in event-received

- terraform/environment/region/ecs.tf
- terraform/environment/region/modules/app/variables.tf
- terraform/environment/region/modules/mock_onelogin/variables.tf
- terraform/environment/region/modules/mock_onelogin/waf.tf
- terraform/environment/region/modules/mock_pay/variables.tf
- terraform/environment/region/modules/mock_pay/waf.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Support turning of WAF association for ITHC
Fixes MLPAB-2269
- Add variable to toggle WAF ALB association per environment
- protect mock pay and mock onelogin ALBs with WAF
> MLPAB-2269 - add toggle for waf alb association and protect mocks

- terraform/environment/region/modules/mock_onelogin/ecs.tf
- terraform/environment/regions.tf
persistent environments were not deploying new images for mock onelogin tagged latest
Fixes MLPAB-2273
- get image digest for latest image
> MLPAB-2273 - use image digest from tag for mock onelogin task def

- terraform/account/kms_key_dynamodb_exports_s3.tf
Limit access to export encryption key
Fixes MLPAB-2203
- let opensearch pipeline role use encryption key in prod and preprod
> MLPAB-2203 - remove app-task-role from dynamodb exports encryption key

- .github/workflows/dispatch_export_sbom.yml
- .gitignore
- scripts/sbom_exporter/export_ecr_image_sbom.sh
Finish self service sbom workflow for docker images
Fixes MLPAB-2343
- checkout code and install aws cli
- upload artifacts for user download
- ~TODO: get sbom for mock onelogin image~
(the mock-onelogin image is producing empty exports, so will address that over on that repository)
> MLPAB-2343 - create a self service SBOM generation workflow in GitHub actions

- terraform/environment/region/modules/s3_antivirus/lambda_function.tf
Lambda's would previously always publish a new version even when nothing had changed about them.
Fixes MLPAB-2011
- Use a terraform_data resource to hold a replacement trigger
- compare SHA256 to replacement trigger to determine when to publish
- https://developer.hashicorp.com/terraform/language/resources/terraform-data
> MLPAB-2011 - only publish lambda when the lambda source changes

- terraform/environment/region/modules/app/alb.tf
- terraform/environment/region/modules/mock_onelogin/alb.tf
- terraform/environment/region/modules/mock_pay/alb.tf
Replace rules to avoid duplicate rule errors
Fixes MLPAB-2383
- Use lifecycle to replace the sgrule resource when allowlist changes
- https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by
> MLPAB-2383 - replace sgrule when allow list changes

- terraform/environment/region/health_checks.tf
After finding some failing checks associated with high latency results, using different checkers may improve uptime reporting
Fixes MLPAB-2414
- use us-west-2 instead of singapore for health checker
> MLPAB-2414 - Improve uptime reporting

- terraform/environment/.terraform.lock.hcl
- terraform/environment/region/modules/app/alb.tf
- terraform/environment/region/modules/mock_onelogin/alb.tf
- terraform/environment/region/modules/mock_pay/alb.tf
Fix demo environment health-checks failing
Fixes MLPAB-2431
- use Oregon region for health-check ingress
- replace public and private rules when toggling public access (also enables recovery from duplicate entries error)
- replace health-check ingress rules when AWS checkers cidr or ipv6 cidr ranges change rather than update in place
- https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by
> MLPAB-2431 investigate demo healthchecks reporting site down

- terraform/environment/dynamodb_cloudtrail.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Log data plane events for Dynamodb
Fixes MLPAB-1659
- create Cloudtrail using existing trial bucket
- only create trails for specific environments
- only log Dynamodb data plane events
- ~encrypt trail~ will be done as part of ticket 2436 as requires account level resources to exist first.
- Only enable for preproduction and production
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/logging-using-cloudtrail.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail
> MLPAB-1659 - create cloudtrail from dynamodb data plane events

- terraform/environment/dynamodb_cloudtrail.tf
- terraform/environment/terraform.tfvars.json
Enable CMK encryption of CloudWatch Log Groups
Fixes MLPAB-2436
- use KMS CMK for log group
- Allow CKM to be used by cloudtrail
> MLPAB-2436 - enable encryption for the dynamodb cloudtrail log group

- terraform/account/region/modules/antivirus_definitions/s3.tf
- terraform/account/region/modules/s3_batch_manifests/s3.tf
- terraform/environment/region/modules/uploads_s3_bucket/s3_bucket_lifecycles.tf
Fixes MLPAB-2499
- add lifecycle policy to abort incomplete multipart uploads after 7 days
- https://aws.amazon.com/blogs/aws-cloud-financial-management/discovering-and-deleting-incomplete-multipart-uploads-to-lower-amazon-s3-costs/
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration
> MLAB-2499 - abort incomplete MPUs after 7 days

- terraform/environment/region/modules/app/alb.tf
- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/region/modules/mock_onelogin/alb.tf
- terraform/environment/region/modules/mock_onelogin/ecs.tf
- terraform/environment/region/modules/mock_pay/alb.tf
- terraform/environment/region/modules/mock_pay/ecs.tf
Allow time to drain requests what new targets are deployed
Fixes MLPAB-2531
- use the default value 300 seconds for deregistration
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group
- https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-register-targets.html
> MLPAB-2531 - set a deregistration delay to address load balancer 4xx errors

- internal/dashboard/store.go
- internal/dashboard/store_test.go
We already filter out the UID-less LPAs, the error we got was actually trying to get LPAs with the empty list `[]`.
> MLPAB-2534 Return dashboard data early when no Lpas with a UID to get

- .github/workflows/docker_job.yml
- cmd/mlpa/buildtrigger
Mitigate impact of rate limiting when scanning images with Trivy
Fixes MLPAB-2565
- Define java db repo and use pass through cache location
- https://aquasecurity.github.io/trivy/v0.55/docs/references/configuration/config-file/#db-options
> MLPAB-2565 - use pull through cache for trivy java db

- .github/workflows/docker_job.yml
- .pre-commit-config.yaml
- docker/event-logger/Dockerfile
- docker/event-received/Dockerfile
- docker/localstack/Dockerfile
- docker/localstack/localstack-init.sh
- docker/mock-notify/Dockerfile
- docker/mock-os-api/Dockerfile
- docker/mock-pay/Dockerfile
- lambda/create_s3_replication_job/Dockerfile
Apply where possible Dockerfile best practices using Hadolint
Fixes MLPAB-2593
- Address Hadolint findings on `create_s3_replication` Dockerfile
- pin package versions
- use no-cache
- don't upgrade pip for consistent builds
- consolidate COPY command
- name final stage as production
- ~TODO: fix log output, should write batch job id (see https://docs.aws.amazon.com/cli/latest/reference/lambda/invoke.html and invocation type dry-run for deployed function)~ created ticket 2596
- Address Hadolint findings on `event-received` Dockerfile
- Double quote to prevent globbing and word splitting.
- Address Hadolint findings on `localstack` Dockerfile
- pin package versions
- use no-cache
- ~COPY to a relative destination without WORKDIR set.~
- Consolidate consecutive RUN commands
- ~update …
> MLPAB-2593 - Use hadolint to improve dockerfiles

- terraform/environment/region/modules/uploads_s3_bucket/s3_object_replication.tf
Resolve unauthorised api call errors for list bucket actions when using the batch manifests role
Fixes MLPAB-2620
- Add list bucket action for batch manifests
- https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html
> MLPAB-2620 - fix issue with access to manifests bucket

- docs/architecture/decisions/0005-namespacing-resources-in-aws.md
- terraform/environment/region/ecs.tf
- terraform/environment/region/ecs_autoscaling.tf
- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/region/modules/app/variables.tf
- terraform/environment/region/modules/ecs_autoscaling/main.tf
- terraform/environment/region/modules/ecs_autoscaling/variables.tf
- terraform/environment/region/modules/mock_onelogin/ecs.tf
- terraform/environment/region/modules/mock_onelogin/variables.tf
- terraform/environment/region/modules/mock_pay/ecs.tf
- terraform/environment/region/modules/mock_pay/variables.tf
- terraform/environment/region/modules/uploads_s3_bucket/lambda.tf
- terraform/environment/region/variables.tf
Remove region from the naming of resources in the environment so that they can be seen as the same across regions for resilience assessment.
Fixes MLPAB-2611
- update ADR on naming resources
- rename ECS and autoscaling resources to remove region when not needed
> MLPAB-2611 - Only use region in resource names when the resource must be globally unique

- terraform/environment/.terraform.lock.hcl
- terraform/environment/regions.tf
Keep the allow list up to date
Fixes MLPAB-2638
- update version of allow list module
- upgrade lockfile
- https://github.com/ministryofjustice/opg-terraform-aws-moj-ip-allow-list
> MLPAB-2638 - update allow list module

- .github/workflows/workflow_destroy_pr_environment.yml
Fix destroy job step that removes log group
Fixes MLPAB-2640
- remove region from log group name
> MLPAB-2640 - remove region from log group name in destroy job

- .github/workflows/workflow_destroy_pr_environment.yml
Destroy job is not using hte correct workspace names
Fixes MLPAB-2640
- use only PR number for destroy job
> MLPAB-2640 - fix workspace name in destroy job

- internal/certificateprovider/certificateproviderpage/identity_with_one_login_callback.go
- internal/certificateprovider/certificateproviderpage/identity_with_one_login_callback_test.go
- internal/donor/donorpage/identity_with_one_login_callback.go
- internal/donor/donorpage/identity_with_one_login_callback_test.go
- internal/event/client_test.go
- internal/event/events.go
- internal/event/events_test.go
- internal/event/testdata/attorney-started.json
- internal/event/testdata/identity-check-mismatched.json
- internal/event/testdata/paper-form-requested.json
- internal/sharecode/sender.go
- internal/sharecode/sender_test.go
Remove URN prefix so it's just the UUID stored in the LPA Store.
To match [event store changes](https://github.com/ministryofjustice/opg-event-store/pull/101)
For CTC-192 #minor
Updated the event structs, then fixed all the now-broken code.
Nothing particular, it wasn't a particularly mentally taxing task.
> Remove URN prefix from actorUID in events

- terraform/account/kms_key_event_recieved_sqs.tf
Use CMK for event received workloads
Fixes MLPAB-2613
- Allow root in dev and event received role in preprod and prod
> MLPAB-2613 - allow event received lambda role to decrypt

- terraform/account/region/network.tf
Apply on PTL failed due to an invalid resource policy
Fixes MLPAB-2740
- upgrade module to add resource policy and use vended logs path
- https://repost.aws/questions/QUyaiOwEY5QxKlMKqGTMRPFw/cannot-enable-logging-policy-document-length-breaking-cloudwatch-logs-constraints-either-1-or-5120
- https://stackoverflow.com/questions/73771271/i-am-getting-issue-in-policy-document-length-breaking-cloudwatch-logs-constraint
> MLPAB-2740 - fix firewall logging

- cypress/e2e/donor/add-correspondent.cy.js
- docker/mock-lpa-store/lpa-store.js
- internal/donor/donordata/correspondent.go
- internal/donor/donordata/provided_test.go
- internal/donor/donorpage/enter_correspondent_address.go
- internal/donor/donorpage/enter_correspondent_address_test.go
- internal/donor/donorpage/enter_correspondent_details.go
- internal/donor/donorpage/enter_correspondent_details_test.go
- internal/donor/donorpage/register.go
- internal/event/events.go
- internal/event/events_test.go
- internal/event/testdata/correspondent-updated.json
To allow the event to work https://github.com/ministryofjustice/opg-event-store/pull/111
> MLPAB-2018 Add a UID to correspondent and send with event

- cypress/e2e/certificate-provider/dashboard.cy.js
- internal/dashboard/store.go
- internal/dashboard/store_test.go
- internal/page/fixtures/certificate_provider.go
- web/template/dashboard.gohtml
> MLPAB-2689: Show dashboard certificate providers until certificate provided and identity confirmed

- terraform/environment/global/iam_egress_checker_lambda_role.tf
- terraform/environment/global/outputs.tf
- terraform/environment/region/egress_checker.tf
- terraform/environment/region/modules/egress_checker/main.tf
- terraform/environment/region/modules/egress_checker/variables.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
Policy documents were being overwritten on each apply toggling api permissions for event received on and off. This was caused by accidental reuse of a role and policy name
Fixes MLPAB-2777
- create role for egress checker
> MLPAB-2777 - create role for egress checker

- internal/dynamo/client.go
- internal/dynamo/client_test.go
For `(SCHEDULEDDAY#, SCHEDULED#)` records we decided to add the `LpaUID` so they could be removed easily, this means they can be returned by `OneByUID` causing issues when only `(LPA#, DONOR#)` is expected.
> MLPAB-1767 Filter OneByUID so it only returns donor records

- cypress/e2e/donor/dashboard.cy.js
- internal/lpastore/lpa.go
- internal/lpastore/lpadata/lpa.go
- internal/lpastore/resolving_service.go
- web/template/dashboard.gohtml
> MLPAB-2637: Add track progress button to dashboard when paid or paying

- terraform/environment/global/iam_ecs_execution_role.tf
- terraform/environment/region/ecs.tf
- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/region/modules/app/variables.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Update the otel collector image used in ECS
Fixes MLPAB-2796
- use var for image tag and allow ecs to pull upstream images
- allow ecs execution role to pull upstream images to update the pull through cache
- https://gallery.ecr.aws/aws-observability/aws-otel-collector
- https://aws-otel.github.io/docs/setup/ecs
> MLPAB-2796 - update the otel collector image used in ECS

- terraform/account/.terraform.lock.hcl
- terraform/account/iam_sns_feedback_role.tf
- terraform/account/refactoring.tf
- terraform/account/region/opensearch.tf
- terraform/account/region/outputs.tf
- terraform/account/region/s3_lb_access_logs.tf
- terraform/account/region/sns_topics.tf
- terraform/account/region/variables.tf
- terraform/account/region/versions.tf
- terraform/account/regions.tf
Make Opensearch serverless resources regional for failover
Fixes MLPAB-2643
- Move opensearch file into region module
- create variables to pass resources and attributes in from root
- use moved blocks to relocate resources to their new address
- https://developer.hashicorp.com/terraform/language/moved
> MLPAB-2643 - refactor opensearch into account level regional resource

- terraform/environment/region/data_sources.tf
- terraform/environment/region/event_bus.tf
- terraform/environment/region/modules/event_bus/data_sources.tf
- terraform/environment/region/modules/event_bus/main.tf
- terraform/environment/region/modules/event_bus/outputs.tf
- terraform/environment/region/modules/event_bus/versions.tf
- terraform/environment/region/pagerduty.tf
- terraform/environment/region/s3_antivirus.tf
Raise an alarm to team if items arrive in the DLQ for Environment event bus. This would be an indication of an invocation failure for the event-received and schedule runner lambda functions
Fixes MLPAB-2602
- add SNS topic for DLQ alarm 
- subscribe Pagerduty to SNS topic
> MLPAB-2602 - Create an alarm for invocation failures from the event bus

- terraform/account/region/load_balancer_access_logs_athena.tf
An error during the production account creation of the athena db has resulted in a db that cannot be updated or deleted. I've opted to create another alongside.
- rename db
I've already checked and applied this to production, and checked preproduction is ok.
> rename athena db to avoid broken db in production

- .github/workflows/workflow_pr.yml
Automate the merging of PRs when they need to be kept up to date with the main branch.
Fixes MLPAB-2857
- (manually) require merge queues in branch protection rules
- Add merge group trigger to PR workflow
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#merge_group
> MLPAB-2857 - Use merge queues

- .github/workflows/workflow_pr.yml
Report the deployment (and required check) as failed when account workflows fail
Fixes MLPAB-2867
- need account workflows
> MLPAB-2867 - require account jobs to pass for end of PR workflow check

- .github/workflows/workflow_merge_group.yml
Run a new workflow in merge queues
Fixes MLPAB-2857
- create merge group workflow
- deploy to staging environment
- identify when running as a merge group trigger and create a pre-release tag
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#merge_group
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
- https://docs.github.com/en/webhooks/webhook-events-and-payloads#merge_group
> MLPAB-2857 - create a new merge group workflow

- renovate.json
To prevent exploits based on compromised repositories and malicious tag updating, use digests when pinning github actions
- add github actions digest helper to renovate config
- https://docs.renovatebot.com/modules/manager/github-actions/#digest-pinning-and-updating
> pin github actions to digests

- .github/workflows/dispatch_deploy_to_ur_environment.yml
The deploy UR job fails because it supplies inputs that are no longer required
Fixes MLPAB-2941
- remove S3 AV lambda zip steps as no longer required
- remove `s3_av_scanner_zip_tag` input from environment deploy job
> MLPAB-2941 - remove s3 av zip lambda setup as deprecated

- terraform/environment/region/modules/event_bus/main.tf
Make it easy for the team to find relevant logs, by creating an insight query in the environment's folder
Fixes MLPAB-2944
- create insight query for emitted events
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_query_definition
> MLPAB-2944 - create insights query for emitted events

- .github/workflows/slack_job.yml
Path to live failure notifications had stopped worked with an error saying the slack token was missing. 
Fixes MLPAB-2947
- Use correct name for slack secret
> MLPAB-2947 - Fix path to live failure notifications

- terraform/account/.terraform.lock.hcl
- terraform/account/opg_metrics.tf
- terraform/account/region/versions.tf
- terraform/account/regions.tf
- terraform/account/terraform.tf
- terraform/account/terraform.tfvars.json
- terraform/account/variables.tf
- terraform/environment/.terraform.lock.hcl
Create a shared api destination for opg-metrics put requests
Fixes MLPAB-2959
- create api destination
- create connection with auth using api key
- put api destination arn in a parameter
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_connection
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_api_destination
> MLPAB-2959 - create eventbridge api destination for opg-metrics

- terraform/account/terraform.tf
- terraform/environment/terraform.tf
Using dynamodb for state locking is now deprecated.
Fixes MLPAB-2966
- set `use_lockfile` to true in S3 backend setup for environment and account level terraform 
- https://developer.hashicorp.com/terraform/language/backend/s3#state-locking
> MLPAB-2966 stop using deprecated state lock mechanism for terraform

- terraform/environment/region/ecs.tf
- terraform/environment/region/modules/app/alb.tf
- terraform/environment/region/modules/app/variables.tf
- terraform/environment/region/variables.tf
- terraform/environment/regions.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Start pages in the app should be redirected to the mainstream content start pages
Fixes MLPAB-2977
- add listener rule for donor start page
- add listener rule for attorney start page
- add listener rule for certificate provider start page 
- https://registry.terraform.io/providers/hashicorp/aws/5.95.0/docs/resources/lb_listener_rule.html
> MLPAB-2977 - redirect starts to mainstream content

- .github/workflows/analysis-codeql.yml
- .github/workflows/analysis-tfsec-pr-feedback.yml
- .github/workflows/analysis-tfsec-to-github-security.yml
- .github/workflows/detect_changes_to_app_job.yml
- .github/workflows/dispatch_change_dns_target_region.yml
- .github/workflows/dispatch_manage_maintenance_mode.yml
- .github/workflows/dispatch_manage_public_access_ur_environment.yml
- .github/workflows/dispatch_trivy_scan_production.yml
- .github/workflows/docker_job.yml
- .github/workflows/document_linting_job.yml
- .github/workflows/go-unit-tests.yml
- .github/workflows/remove_ingress_job.yml
- .github/workflows/schedule_update_opg_metrics_credentials.yml
- .github/workflows/tags_job.yml
- .github/workflows/terraform_account_job.yml
- .github/workflows/terraform_environment_job.yml
- .github/workflows/ui_test_job.yml
- .github/workflows/workflow_destroy_pr_environment.yml
- .github/workflows/workflow_terraform_environment_cleanup.yml
- terraform/account/opg_metrics.tf
OPG Metrics rotates credentials on a daily basis. Lambda functions using OPG Metrics directly fetch API keys, but Event Bridge API destinations store a copy of the credentials. 
Fixes MLPAB-2991
- Schedule a job after the API key rotation (2am) to update the stored credential
- Pin checkout action to patch version
- Remove AV lambda zip related jobs from UR job
- ignore invocation_http_parameters changes (this was triggering a removal of an empty attribute)
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
> MLPAB-2991 - schedule targetted apply for api destination credentials

- terraform/environment/.terraform.lock.hcl
- terraform/environment/versions.tf
metadata in a hashicorp/local provider version causes a error exit when querying available versions during init. We no longer use the provider so we can remove it
- remove hashicorp/local
> remove unused provider

- lang/cy.json
- lang/en.json
- web/template/layout/changeable-contextual-lpa.gohtml
- web/template/layout/contextual-lpa.gohtml
- web/template/layout/text-summary-row.gohtml
I've used HTML rather than one of the `summary-row` partials here as the combo of needing to suppress a heading (while remaining semantically correct) + add placeholder text was making the templates too complex.
Fixes MLPAB-2971
> MLPAB-2971: Add placeholder text when no restrictions

- .gitignore
- cypress.config.js
- package.json
- playwright.config.js
- playwright/complete-donor-flow.spec.js
- playwright/e2e.js
- playwright/textExtractor.js
- playwright/textExtractor.test.js
- web/template/donor/your_legal_rights_and_responsibilities.gohtml
- yarn.lock
I tried a couple of approaches here.
Firstly, trying to utilise existing handler unit tests would have been a way to make the tests part of the app code but it required some clunky setup and (as you'll see from the screenshot) needs a populated LPA/template data to work and so lots of extra scaffolding in all tests so I've disregarded this.
Then I tried to extract the content using a custom text extractor script. Its not pretty but its got things in the format I was looking for.
Lastly I bought in a 3rd party package to try extracting it as markdown.
You can see the results of both in zips on the ticket for a comparison of the formatting or run yourself with the new commands added to package.json.
Fixes MLPAB-2975
> MLPAB-2975: Extracting content for review

- docker/create-s3-replication-job/Dockerfile
- docker/event-received/Dockerfile
- docker/schedule-runner/Dockerfile
To upgrade various vulnerable packages
#patch
Used latest release of lambda/provided and its hash
AWS doesn't seem to publish hashes on their directory so I had to fetch it locally
> Bump lambda/provided image to latest

- docs/runbooks/adding-otel-collector-to-lambdas.md
Keep Otel collector up to date
Fixes MLPAB-3073
- update runbook with available versions
- pull latest collector version
- https://aws-otel.github.io/docs/getting-started/lambda/lambda-go#lambda-layer
> MLPAB-3073 - check for and update the aws otl collector

- Makefile
- docker/schedule-runner/.trivyignore.yaml
- docker/schedule-runner/Dockerfile
Fixes MLPAB-3084
- reuse solution for resolving sqlite vuln in event-received
- add trivy ignore
- location of metric query for test-schedule-runner make target has changed
I checked this with the test-schedule-runner make target
> MLPAB-3084 - reuse sqlite solution from event-received

- internal/page/fixtures/attorney.go
We were contacting every attorney every time an email was provided. This made it difficult/impossible to use the access code of a specific attorney as the sharecode needs to be unique so is only used once. Now we can filter by who we want to receive the email and log in as.
> Allow specifying which attorney recieves sharecode email

- cypress/smoke/smoke.cy.js
As this assertion only runs on preproduction it wasn't caught in the PR smoke test.
Fixes MLPAB-3129
> MLPAB-3129: Update preproduction cypress smoke test

- terraform/environment/data_sources.tf
- terraform/environment/dynamodb.tf
Use resource policies to control who can access customer data
Fixes MLPAB-3127
- add a resource policy to DynamoDB table
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/access-control-resource-based.html
> MLPAB-3127 - add resource policy to main table

- terraform/environment/region/modules/uploads_s3_bucket/lambda.tf
Save costs while there are far fewer objects to replicate
- set lamdab trigger schedule to 1 hourly
> reduce schedule to hourly

- .github/dependabot.yml
To try to fix the failing dependabot PRs as it looks like slashes in the branch name could be problematic.
> Set dependabot branch names seperator to dashes

- terraform/environment/region/modules/app/variables.tf
- terraform/environment/region/modules/mock_pay/variables.tf
- terraform/environment/regions.tf
Obscure allowed CIDR ranges from github actions logs
Fixes MLPAB-3167
- make cidr range input variables sensitive
- https://developer.hashicorp.com/terraform/language/values/variables#suppressing-values-in-cli-output
> MLPAB-3167 - Obscure CIDR ranges

- terraform/environment/region/modules/app/ecs.tf
- terraform/environment/terraform.tfvars.json
Domain root of demo environment redirects to production guidance
Fixes MLPAB-3211
- fix env vars for when no input is given for start urls
- fix tfvars for demo env
> MLPAB-3211 - fix go app redirects
